- build.json
With this the size of build.js goes from 398K to 107K.
Note: it is necessary to set "unknownDefines" to "off" not to get the following error:
```
node tasks/build.js build.json geoportailv3/static/build/build.js
info geoportailv3 Parsing dependencies
info geoportailv3 Compiling 376 sources
ERR! compile ERROR - unknown @define variable goog.json.USE_NATIVE_JSON
ERR! compile 
ERR! compile 1 error(s), 0 warning(s), 
ERR! compile 97.7% typed
ERR! compile 
ERR! Process exited with non-zero status, see log for more detail: 1 
make: *** [geoportailv3/static/build/build.js] Error 1
```
> Remove exports from build.js

- CONST_vars.yaml
This PR uses a more specific pyramid_closure `root` for ngeo. This is to avoid problems when using a built ngeo source tree (with `ngeo.js` and `ngeo-debug.js` in `dist/`).
> More specific pyramid_closure root for ngeo

- geoportailv3/static/js/layermanager/layermanagerdirective.js
Fixing the issue with layer manager not showing on built version.
Please review.
> Prevent injected service from being renamed

- requirements.txt
This is to workaround https://github.com/Toblerity/Shapely/issues/231, which prevents us from installing Shapely 1.5.4.
Let's see what Travis says.
Fixes #167.
> Use Shapely 1.5.3

- geoportailv3/static/js/backgroundlayer/backgroundlayer.html
- geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js
- geoportailv3/static/js/main.js
- geoportailv3/static/js/maincontroller.js
- geoportailv3/templates/index.html
- less/sidebar.less
This PR adds a background layer selector based on Angular UI Bootstrap's `dropdown` directive and ngeo's `ngeoBackgroundLayerMgr` service.
This is what it looks like for the moment:
Work on the CSS is needed. In particular, the list is not correctly centered:
Things to do:
> Add background layer selector

- geoportailv3/static/js/maincontroller.js
- geoportailv3/static/less/navbars.less
- geoportailv3/templates/index.html
The goal of those changes is to prepare the work for the toolboxes (button with an attached panel which open when the button is clicked).
We use a ngeo-btn-group so that when a toolbox panel is shown the other toolboxes are hidden.
The same work needs to be done for the top right buttons (login, languages).
> Panels for tools using ngeo-btn-group

- geoportailv3/static/js/layermanager/layermanager.html
- geoportailv3/static/js/layermanager/layermanagerdirective.js
With this pull request, the opacity and visibility now work together.
Moving the opacity slider to the left will display a slashed eye.
Clicking on the eye will change the opacity to 0 and thus will move the slider automatically to the left.
When the slashed eye is clicked:
- the opacity is changed to 1 if the slider was manually moved to the left,
- the opacity is changed to the previously known opacity if the visibility was changed by clicking on the eye.
> Opacity and visibility interaction

- geoportailv3/static/js/maincontroller.js
- geoportailv3/templates/index.html
This PR removes the `mainCtrl.sidebarOpen` state and the four watchers that are necessary to keep it in sync with `layersOpen`, `mymapsOpen` and `infosOpen`.
With this PR we go from 243 to 239 watchers, 208 of which coming from the catalog directive (with the per-node watchers we need).
>  Remove mainCtrl.sidebarOpen

- CONST_Makefile
This is to prevent 404s on source map files in non-debug mode.
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/201.
> Remove sourceMappingURL from build.js

- geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js
- geoportailv3/static/js/catalog/catalogdirective.js
- geoportailv3/static/js/themesservice.js
- geoportailv3/templates/index.html
This PR adds an `appThemes` service to the project's Angular application. This service requests the "themes" data from c2cgeoportal's `themes` web service, and provides functions to interact with that "themes" data. The service is used by the catalog and background layer directives.
Now that the background layer directive gets the list of background layers from the "themes" web service, we have 5 background layers in the background layer selector. BUT only two layers actually work: `basemap_global` and `topogr_global`. I would suggest that we look at the non-working background layers after merging this.
Please review.
> Add an appThemes service

- geoportailv3.mk
- geoportailv3/static/less/geoportailv3.less
This PR fixes the path to font-awesome fonts.
See https://github.com/Geoportail-Luxembourg/geoportailv3/commit/a6b8e9edafbec42245cb8706ba7b41d196ddc228#commitcomment-9981500.
Fixes #289.
> Fix font awesome path

- geoportailv3/static/js/layerfactoryservice.js
When creating a WMS layer the `layers` node attribute should be used as the `layers` parameter in WMS GetMap requests.
Please review.
Fixes #140.
> Use "layers" node attribute as WMS "layers" param

- CONST_Makefile
- geoportailv3/templates/index.html
As discussed in https://github.com/Geoportail-Luxembourg/geoportailv3/pull/250 `proj4.js` (the minified version) should be added/concatenated to the `build.js` build.
Fixes #307.
> Add proj4 to build.js

- geoportailv3/static/js/measure/measuredirective.js
This commit fixes a bug where the measure tools were not disabled when closing the measure menu. The problem only exists in non-debug mode. It is related to the "active" property being renamed by the compiler. The fix involves using setActive instead of setting the "active" property directly.
Fixes #319
> Disable measure tools when measure menu is closed

- geoportailv3/static/js/infobar/projectionselector.html
- geoportailv3/static/js/infobar/projectionselectordirective.js
This PR makes use of the `ngeo-control` directive for adding the mouse position control to the info bar.
Fixes #310.
> Use ngeo-control for mouse position control

- CONST_Makefile
- build.json
- geoportailv3/static/js/authentication/authentication.html
- geoportailv3/templates/index.html
- templatecache.mako.js
Currently, the directive partials are downloaded by Angular with XHR requests at application init time, in both debug and non-debug mode. With this PR the directive partials are added to `build.js`, thereby avoiding extra requests in non-debug mode. The behavior is unchanged in debug mode: directive partials are still downloaded at application init time.
Please review.
Fixes #176.
> Pre-cache directive partials

- CONST_versions.txt
This set `js.jqgrid` to `4.1.0` in `CONT_versions.txt`, to be in conformance with https://github.com/camptocamp/c2cgeoportal/pull/1278.
Fixes #281.
> Set js.jqgrid version to 4.1.0 in CONST_versions.txt

- geoportailv3/static/js/catalog/catalogdirective.js
As far as I understand the `CatalogController::getInfo` is not used.
Let's remove it.
Please review.
> Removing unused getInfo method

- build.json
With https://github.com/camptocamp/ngeo/pull/187 the ngeox.js externs file depends on externs defined in the typeahead.js externs file. So this requires adding the typeahead.js extens file to the project't build.json configuration file.
> Add the typeahead.js externs file

- geoportailv3/static/js/layermanager/layermanagerdirective.js
The goal here is to manage the old opacities internally instead of creating a new property in the layer.
> oldOpacity can be managed internally, don't create layer property

- elemoine.mk
Before that PR I used `PRINT_OUTPUT = /tmp` in `elemoine.mk` to prevent the `print` target from failing. But that actually did not work as expected. This is the error I'm getting:
```
mv /tmp/print-elemoine.war /tmp
mv: ‘/tmp/print-elemoine.war’ and ‘/tmp/print-elemoine.war’ are the same file
make: *** [/tmp/print-elemoine.war] Error 1
```
This PR uses a better way to disable the `print` target in my environment. This is done by adding `print` to `DISABLE_BUILD_RULES`.
> Use a better way to disable print target

- geoportailv3/static/js/themesservice.js
As [noticed](https://github.com/Geoportail-Luxembourg/geoportailv3/commit/9614a7b3fff29b23c3ff00fc000a278afbae3886#commitcomment-10363813) by @pgiraud we can use `module.service` rather than `module.factory` for the `appThemes` service.
> Use module.service for appThemes

- geoportailv3/static/js/map/mapdirective.js
- geoportailv3/static/js/statemanagerservice.js
Fix a bug where the map directive converts x, y and zoom from version 2 to version 3 when the values are read from the local storage. There should be no conversion when the values are read from the local storage. The conversions occur only when reading from the location URL, when there's no version parameter or when the version parameter is set to 2.
Depends on https://github.com/camptocamp/ngeo/pull/203.
Fixes #372.
> Fix localStorage/permalink bug

- geoportailv3/static/js/catalog/catalogdirective.js
- geoportailv3/static/js/catalog/layertreenode.html
- geoportailv3/static/less/catalog.less
I worked on the checkboxes in the catalog tree.
The idea was to push the checkboxes to the right. However I didn't find any way to make it correctly accessible.
I strongly think that it's a good thing to link the label (layer name) with the checkbox and group them into one single clickable element. Aligning the checkbox to the right makes things technically harder.
So, though it's a bit less comfortable visually, I think it works very well with what i did.
> Better looking and more accessible checkboxes

- print/print-apps/geoportailv3/requestData.json
this is a new sample with a working WMTS layer and a setting for the scalebar to use the LUREF coordinate system rather than webmercator.
the sample has been tested with the latest standalone print jar.
> new print sample

- build.json
- geoportailv3/static/js/locationcontrol.js
- geoportailv3/static/js/maincontroller.js
- geoportailv3/static/js/measure/measuredirective.js
- geoportailv3/static/js/profile/profiledirective.js
This PR fixes new compile errors that we now get because we use a more recent version of Closure Compiler.
See also https://github.com/camptocamp/ngeo/pull/207 and https://github.com/openlayers/ol3/pull/3511.
> Fix compile errors

- CONST_requirements.txt
This commit makes pip download a zip archive for Pyramid instead using git. Using git leads to proxy-related issues, even if git+https is used, because Pyramid itself uses the git protocol for its pylons_sphinx_theme.git submodule.
Fixes #269.
> Make pip download a zip for Pyramid

- geoportailv3/static/js/layeropacitymanagerservice.js
- geoportailv3/static/js/maincontroller.js
This commit adds a layer opacity manager service responsible for resetting the opacity of layers added to the map.
Fixes #381.
> Add a layer opacity manager

- geoportailv3/static/js/profile/profile.html
- geoportailv3/static/js/profile/profiledirective.js
This pull request aims to add an interaction between map and profile chart.
Please ensure that the `templatecache.js` file is updated.
I'm not super satisfied with the usability of the whole component for the following reasons:
- the length of the line stays displayed and the hover tooltip may be displayed behind the length tooltip,
- the tooltip "click to start drawing" is annoying once a line is drawn,
- the point which shows the "hovered" distance is not visible enough.
Maybe we should:
- remove the length tooltip once the line is drawn,
- deactivate the measure length interaction until the user explicitly wants to draw a new line (button "new profile" somewhere).
> Adding map->profile interaction

- geoportailv3/static/js/layerfactoryservice.js
- geoportailv3/static/js/themesservice.js
Fixes #355.
To be tested. But testing this requires a `themes` response with the `imageType` information.
> Get image type from layer spec

- CONST_Makefile
This was removed in https://github.com/Geoportail-Luxembourg/geoportailv3/commit/c2ec0fa0d213e1afc86f487d5dc0572a9b74f7c5.
@sbrunner, this will need to be backported to c2cgeoportal.
> Rebuild template cache when directive partials change

- geoportailv3/static/js/statemanagerservice.js
With this commit we just don't use the localStorage if it's not available. In particular the localStorage is not available in Safari when the private mode is used.
@jaykayone, I couldn't fully test this commit as Chrome in incognito mode still allows to read/write from/to the localStorage. It's a simple change, so we could merge it and then have you test it again.
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/438.
> Do not try to use localStorage if not available

- build.json
This is to follow a recent change made to the pyramid_closure scaffold: https://github.com/camptocamp/pyramid_closure/pull/54.
> Set closure compiler language in to ECMASCRIPT5_STRICT

- build.json
Use `--export_local_property_definitions` in preparation for https://github.com/camptocamp/ngeo/pull/216.
> Use export_local_property_definitions Closure Compiler flag

- geoportailv3/static/js/themeswitcher/themeswitcherdirective.js
Previously a theme that did not have `display_in_switcher` set could be considered valid. This PR changes that. To be valid the theme just needs to be present in the list of themes received from the server.
@rmichaelis, could you please review this?
> To be valid a theme need not be displayed in switcher

- build.json
- elemoine.mk
- geoportailv3/static/js/layerfactoryservice.js
- geoportailv3/static/js/print/print.html
- geoportailv3/static/js/print/printdirective.js
- geoportailv3/templates/index.html
- vars_elemoine.yaml
This PR uses the new ngeo print services (https://github.com/camptocamp/ngeo/pull/204) to connect the print directives to the MapFish Print web service.
At this point only WMTS and single tile WMS layers are supported. Supporting printing vectors will be done with separate PRs.
Some UI-related work remains to be done. For example, there's no "wait" icon/message while the user waits for the generation of the print report. And there's no error message displayed when the MapFish Print service returns an error.
Yet, I think this can be reviewed and merged as-is.
> Connect print directive to MapFish Print web service

- .jshintrc
- package.json
This updates jshint to the latest version and get replace `"sub"` by `"-W069"` in the `.jshintrc` file, as using `"sub"` is [deprecated](https://github.com/camptocamp/schweizmobil_re3/pull/216).
> Update jshint to latest stable version

- geoportailv3/static/js/print/printdirective.js
- print/print-apps/geoportailv3/a0_landscape.jrxml
- print/print-apps/geoportailv3/a0_portrait.jrxml
- print/print-apps/geoportailv3/a1_landscape.jrxml
- print/print-apps/geoportailv3/a1_portrait.jrxml
- print/print-apps/geoportailv3/a2_landscape.jrxml
- print/print-apps/geoportailv3/a2_portrait.jrxml
- print/print-apps/geoportailv3/a3_landscape.jrxml
- print/print-apps/geoportailv3/a3_portrait.jrxml
- print/print-apps/geoportailv3/a4_landscape.jrxml
- print/print-apps/geoportailv3/a4_portrait.jrxml
- print/print-apps/geoportailv3/config.yaml
- print/print-apps/geoportailv3/requestData.json
This PR removes the "description" field from the print config.
@jaykayone could you please review this? I am not sure about the changes to the MapFish Print config. I just removed every line that included "description" :-)
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/469.
> Remove print description

- geoportailv3/static/js/print/printdirective.js
The print directive shouldn't assume that the print mask is displayed when the "open" watcher reports that "open" is false. Indeed, we get "open is false" each time another panel is opened.
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/480.
> Fix bug in print directive

- geoportailv3/static/js/print/print.html
- geoportailv3/static/js/print/printdirective.js
This PR adds an exported `cancel` function to the print directive's controller. This function is to be called from the print directive's template when the user presses a "cancel print" button.
At this point the `cancel` function just cancels the current print request, if any. In addition, it should also send a "cancel job" to MapFish Print, but c2cgeoportal's `printproxy` does not currently support that operation. See https://github.com/camptocamp/c2cgeoportal/issues/1357.
Requires https://github.com/camptocamp/ngeo/pull/222.
Please review.
> Add a cancelPrint function to the print directive controller

- geoportailv3/static/js/print/printdirective.js
As discussed with @pgiraud this PR changes the print scale to the optimal scale when the user changes the print layout. This prevents the bad experience that occurs when selecting A0 and not seeing the print mask because it's outside the current viewport.
> Change scale to optimal when changing print layout

- geoportailv3/static/js/catalog/layertreenode.html
Use one-time binding again in the catalog tree node template, and reduce the number of watchers from 1609 to 941 (for the "main" theme).
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/475.
> One-time binding in the catalog tree node template

- geoportailv3/static/js/print/printdirective.js
- geoportailv3/templates/index.html
With this PR the print directive uses the current's print scales (`print_scales` in the theme's `metadata`) instead of using a fixed set of scales.
@jaykayone, could you please review this?
> Use current theme's print scales

- geoportailv3/static/js/infobar/infobar.html
Question for @pgiraud , how to change the infobar icon to use same iconset and method like other icons on page ? for the moment, the infobar icon on mobile does not look as wanted.
> WIP - Infobar adaptations for mobile

- geoportailv3/static/js/search/search.html
- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/static/less/layout.less
- geoportailv3/static/less/search.less
- geoportailv3/static/less/sidebar.less
- geoportailv3/templates/index.html
With this pull request I add the ability to do some search in devices with small screens (ie. mobile device).
When the user clicks on the _magnifier_ button, all the elements in the top bar are hidden, and the search input is displayed as well as a _cross_ button to get back to initial top bar.
This was a bit tricky and I'm not completely confident whether or not it will work on all devices.
There's also a usability issue for now since it would be good to have the keyboard being automatically shown when search input is displayed. Simply invoking `focus` on the input unfortunately doesn't seem to work on mobile devices (at least on safari iOS). I google a bit and tried several options without success.
Note : the list of results displays the same as in large screen devices.
> Mobile specific layout for search input

- geoportailv3/static/js/locationcontrol.js
- geoportailv3/static/js/maincontroller.js
- geoportailv3/static/js/profile/profiledirective.js
- geoportailv3/static/js/query/querydirective.js
- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/static/js/vectoroverlay.js
- package.json
This PR removes the `FeatureOverlay`s and adds an `appVectorOverlay` service that components can use in place a `FeatureOverlay`.
The use of `appVectorOverlay` in a component is as follows:
```js
var index = appVectorOverlay.getIndex();
appVectorOverlay.addFeature(feature, index);
appVectorOverlay.removeFeature(feature, index);
appVectorOverlay.clear(index);
```
The `index` returned by `getIndex` can be seen as handle or a cookie that you need to use in subsequent operations.
This needs reviews and testing.
Please at least review the changes to the components you created in the first place.
> Replace ol.FeatureOverlay by appVectorOverlay

- geoportailv3/static/js/print/printdirective.js
I hope this PR fixes the problem reported by @jaykayone in #489. This works by using ol3's `ol.Projection#getPointResolution` function to use a corrected resolution/scale.
I'd suggest that we merge this and have Jeff test it on the staging server.
Fixes #489.
> Use getPointResolution to correct the print scale

- geoportailv3/static/js/locationinfo/locationinfo.html
- geoportailv3/static/js/locationinfo/locationinfodirective.js
@petzlux Can you please give this a review?
In my opinion, the `featureOverlayItemExists` isn't really useful. To me, ```appSelector == 'locationinfo'``` already does the job.
> Remove unrequired featureOverlayItemExists property

- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/templates/index.html
fix #603 
This pull request will reload the layer search when themes reload, to take into account layers available only to certain user roles
> Search protected layers

- geoportailv3/static/js/print/printdirective.js
- geoportailv3/static/js/profile/profiledirective.js
- geoportailv3/static/js/query/querydirective.js
- geoportailv3/static/js/vectoroverlay.js
With this PR the vector layer used by vector overlays is printed.
Fixes #595.
Requires https://github.com/camptocamp/ngeo/pull/252.
> Vector overlay print support

- geoportailv3/static/js/print/printdirective.js
With this commit the smallest print scale is selected if there is no optimal scale for the current map resolution. This fixes a bug when an "infinite" scale was used.
Fixes #665.
Requires https://github.com/camptocamp/ngeo/pull/258.
> Select the smallest print scale if no optimal

- geoportailv3/static/js/print/printdirective.js
to avoid symbol scaling problems. a better solution will be implemented later on
> go back to 96 dpi resolution in print 

- geoportailv3/static/js/print/printdirective.js
This PR, together with https://github.com/camptocamp/ngeo/pull/261, fix the following vector printing bug:
* Point features displayed by the search component are not printed.
* MapFish Print raises an exception when the vector layer is empty.
Fixes #663.
> Fix vector printing bugs

- geoportailv3/locale/de/LC_MESSAGES/geoportailv3-client.po
- geoportailv3/locale/en/LC_MESSAGES/geoportailv3-client.po
- geoportailv3/locale/en/LC_MESSAGES/geoportailv3-server.po
- geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-client.po
- geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-server.po
- geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-client.po
- geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-server.po
- geoportailv3/static/js/exclusionmanagerservice.js
- geoportailv3/static/js/notifyservice.js
- geoportailv3/static/js/share/sharedirective.js
- package.json
The angular gettext translation string extractor simply does string matching for finding translation strings.
This means that renamed methods such as `this.translate_` wont work for string extraction. 
````
this.translate_ = gettextCatalog;
gettextCatalog.getString('string1'); // gets extracted
gettext('string2'); // gets extracted
gettextCatalog.getPlural(n, 'singular', 'plural'); // gets extracted correctly as one single/plural pair string
var string3 = 'string3'; // string does not get extracted
gettextCatalog.getString(string3) // will not be translated as string is not extracted
this.translate_.getString(string3) // will not be translated
var string4 = gettext('string4'); // string gets extracted
gettextCatalog.getString(string4) // will be translated as string is extracted …
```
> Translations - update of tools and plural translations

- geoportailv3/static/js/query/querydirective.js
`map.forEachLayerAtPixel()` is a costly operation. We should not do that operation while the map is being dragged.
This makes panning the map much faster for me on FF Linux. And it should improve the pan performance in other browsers as well.
Please review.
Fixes #769.
> Do not query the map while dragging the map

- package.json
With this commit we use https://github.com/xx/yy#master rather than xx/yy#master in package.json when specifying dependencies downloaded from GitHub. In this way, npm doesn't attempt to download the package from registry.npmjs.org; instead it goes directly to GitHub. This prevents a failure at npm install time when the content of the 404 response from registry.npmjs.org is empty. It also makes things a bit faster as well.
> Use git+https://github.com/ in package.json

- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/static/less/search.less
- package.json
We're [updating](https://github.com/camptocamp/ngeo/pull/283) ngeo with version 0.11.1 of typeahead.js. This PR accommodates this update.
Please review and test.
When reviewed and tested I'll merge https://github.com/camptocamp/ngeo/pull/283 and this PR.
> Use typeahead.js 0.11.1

- CONST_Makefile
Recent updates to the angular-1.4 externs cause the following compilation error:
```
ERR! compile .build/externs/angular-1.4.js:2234: ERROR - Bad type annotation.  missing closing )
ERR! compile * @typedef {function(Function, number=, boolean=, ...=):!angular.$q.Promise}
```
Fixing the problem requires using a more recent version of Closure Compiler. There's https://github.com/openlayers/closure-util/pull/67, but it's not merged yet. In the mean time this commit uses a specific commit when downloading the closure-compiler externs.
Fixes #840.
> Use closure-compiler commit 5ff0611 for externs

- CONST_Makefile
OpenLayers master now uses the most recent version of Closure Compiler. See https://github.com/openlayers/ol3/pull/4072. So we can use the most recent version of the Angular and jQuery externs again.
> Use closure-compiler#master for externs again

- geoportailv3/static/js/catalog/layertree.html
This fixes a regression introduced by d42e5a4, where the catalog tree is not updated when switching themes. This commit removes the use of one-time binding that causes that problem.
Fixes #837.
> Remove one-time binding in catalog

- build.json
- geoportailv3/externs/typeahead.js
- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/static/less/search.less
- geoportailv3/templates/index.html
- package.json
This reverts the upgrade to typeahead 0.11.1. See #839 for details on why this revert is necessary.
Fixes #839.
> Switch back to typeahead 0.10.5

- geoportailv3/static/js/draw/drawdirective.js
This PR changes the draw directive to encode drawn features in the URL. At init time the directive also decodes the features set in the URL and adds them to the collection of drawn features.
Two things to note:
* At this point features are not added to the local storage. I don't think this is something we've discussed yet.
* #845 is not implemented yet, as there is no notion of mymaps map in the code at this point.
> Permalink feature encoding/decoding

- geoportailv3/static/js/draw/drawdirective.js
This PR fixes a number of feature URL encoding/decoding issues:
- encode the feature style properties instead of encoding the feature styles
- do not encode internal properties such as `__editable__`
- give decoded features correct style values (with correct types)
- re-encode features on feature change
Requires https://github.com/camptocamp/ngeo/pull/323.
> Fix feature encoding/decoding issues

- build.json
This compile option does not exist anymore. And we get a compile error when using a recent version of the compiler.
> Do not use checkStructDictInheritance

- elemoine.mk
This is to prevent CONST_Makefile from searching the "tomcat" directory.
> Set TEMPLATE_EXCLUDE in elemoine.mk

- geoportailv3/static/js/print/printdirective.js
The `layout` and `scale` properties of `app.PrintController` are defined using the bracket notation. For example, this is how the `layout` property is defined in the constructor:
```js
/**
* @type {string}
*/
this['layout'] = this['layouts'][0];
```
So when accessing these properties the bracket notation must be used as well. Do not ever mix the bracket and dot notations for a given property.
> Prevent property renaming in print directive

- CONST_vars.yaml
With a recent version of c2c-template being more strict on variables, the build doesn't pass.
The two missing config variables are "layers" and "reset_password".
I don't know if removing them from `CONFIG_VARS` in `CONST_Makefile` is a good idea, though.
@sbrunner can you please confirm?
Note: this is a blocker bug for now.
> Remove config vars to avoid errors with c2c-template

- CONST_Makefile
- CONST_dev-requirements.txt
- templatecache.mako.js
This PR changes `templatecache.mako.js` to use the `htmlmin` package rather than minifying the HTML code ourselves.
The original problem was found by @pgiraud, where our code just blindly removed newline characters.
And
```html
<button>test</button>
<button>test</button>
```
is not the same as
```html
<button>test</button><button>test</button>
```
@pgiraud, could you please test this?
> Use htmlmin in templatecache.mako.js

- geoportailv3/mymaps.py
- geoportailv3/static/js/draw/drawnfeaturesservice.js
- geoportailv3/static/js/mymapsservice.js
- geoportailv3/views/mymaps.py
Fixes #1110 
It seems that the name "id" as a feature property name is reserved by mapfish-print.
When some features have the same id value, it causes the "feature" to not be printed.
Then to bypass the problem we use "fid" instead of "id".
> Use fid property name instead of id property name

- geoportailv3/static/js/query/querydirective.js
forEachLayerAtPixel was not working with the blank layer.
> Only layers having a source (not the blank layer)

- geoportailv3/static/js/themeservice.js
- geoportailv3/templates/index.html
Record a visit using the right Piwik Site ID. This will also record a separate visit if user changes the Theme.
> Set Piwik Site ID to theme

- geoportailv3.mk
Makes sure that travis builds the api as well
> Add build-api to build target dependencies

- jsapi/src/main.js
It breaks image loading
We don't need it if don't manipulate pixels
> No crossOrigin anonymous

- jsapi/examples/marker.js
- jsapi/externs/luxx.js
- jsapi/src/main.js
With this pull request the position of the marker is now correctly taken into account. Also, it's possible to specify the coordinates system with `positionSrs`.
@tonio please review.
> Position of marker can is LUREF by default

- geoportailv3/static/less/geoportailv3.api.less
- jsapi/examples/search.html
- jsapi/examples/simple.html
- jsapi/src/main.js
Make it so styling for mouse position or background selector controls is applied only when added to the map.
> Less intrusive CSS for controls

- geoportailv3/static/js/appmodule.js
- geoportailv3/static/js/draw/featurepopupdirective.js
- geoportailv3/static/js/exportservice.js
- geoportailv3/static/js/mymaps/mymapsdirective.js
With this pull request the sanitizeFilename is declared only once.
Also the regexp has been improved.
```js
name.replace(/\s+/gi, '_')
name.replace(/[^a-zA-Z0-9\-]/gi, '')
```
is changed to
```js
name.replace(/\s+/g, '_')
name.replace(/[^a-z0-9\-\_]/gi, '')
```
First regexp doesn't need to be case insensitive.
Underscores are not removed any more in the second one.
Also, because the second one is case insensitive, we don't need to search for "A-Z", "a-z" is already removing upper cased characters.
Please review.
> Factorize and enhance sanitizeFilename method

- geoportailv3.mk
- geoportailv3/static/js/search/searchdirective.js
- geoportailv3/templates/index.html
- vars_geoportailv3.yaml
Fixes #1249 
@jaykayone Please test on dev/renaud
configurable in vars_main.yaml like that : 
exclude_theme_layer_search: pag,agriculture
I'm not happy with the key name, if you have a better idea, you are welcome.
> Configure theme without automatic addition of the parcel layer

- jsapi/examples/marker.js
- jsapi/externs/luxx.js
- jsapi/src/main.js
- Use `click: true` options in `features` and `showMarker` to switch from hover to click mode.
- Use `target` on both to render popup content in external dom element.
Fix #1526
> Make showMarker & showFeatures coherent.

- geoportailv3/static/less/featurepopup.less
This is a minor css enhancement to the poi-feature form:
- better padding above the footer buttons
- only allow vertical resize to the textarea
before:
after:
> Minor css fixes to poi-feature form

- geoportailv3/static/js/layermanager/layermanager.html
- geoportailv3/static/less/icons.less
- geoportailv3/static/less/layermanager.less
- fix dragged element height on firefox
- hide the options menu when dragging
- remove the text slide
fixes #1036 
tested on chrome, firefox and IE11
> Fix layer manager drag element styling

- geoportailv3/static/js/mymapsservice.js
- geoportailv3/static/js/print/printdirective.js
In ngeo print service when a text rotation is provided, then text alignment is set to center.  Text aligment in Geoportail is left. https://github.com/camptocamp/ngeo/blob/master/src/services/print.js#L755
> Same alignment both in the print and on the screen

- CONST_vars.yaml
- geoportailv3.mk
- geoportailv3/templates/index.html
- package.json
See https://jira.camptocamp.com/browse/GSLUX-16.
Switched to the Camptocamp maintained fork of Cesium.
With that version, the camera was always blocked by the terrain, as expected.
> [3d] Fix under terrain issue

- geoportailv3/static/js/maincontroller.js
- geoportailv3/templates/index.html
Having 3D disabled by default makes it possible to merge 3D code in master without impact to the production.
The 3D code will be dormant until the project is complete and the features go live.
Being able to merge regularly to master avoid the two branches to diverge and share common work like updating the dependencies and modernizing the code.
> Disable 3D by default

- CONST_requirements.txt
- geoportailv3/static/js/olcs/lux3dmanager.js
Exaggerating terrain requires finer terrain. The previous terrain optimization (loading only a subset of the terrain) was producing artefacts with a terrain exaggeration of 2; it is now disabled by default.
2 parameters can now be passed in the URL:
- terrain_exaggeration=float
The terrain will be exaggerated of that value. When the parameter is missing, defaults to 2.0.
- terrain_levels=<coma separated list of zoom levels>
The terrain levels dowloaded by Cesium will be restricted to the provided ones. When parameter is missing, defaults to all. Example: "terrain_levels=8,11,14,16,17" (old default).
> Exaggerate terrain and load all terrain

- geoportailv3/static/js/olcs/lux3dmanager.js
See https://cesiumjs.org/Cesium/Build/Documentation/Fog.html for the default Cesium values and meanings for the new URL parameters:
- fog_sse_factor
- fog_density
> Allow to customize the fog

- geoportailv3/static/js/olcs/lux3dmanager.js
Allow displaying the 3d tiles coordinates for debugging purpose.
Add the tile_coordinates parameter in the URL.
It is possible to adjust quality by  tweaking the following parameters (see commit for details):
- fog_sse_factor;
- fog_density.
Related to https://jira.camptocamp.com/browse/GSLUX-28.
> Display tile coordinates

- geoportailv3/static/js/wmsservice.js
- package.json
- Link last version of Cesium that has a better support of custom projection.
- Set in lux layers if they support Cesium projection (4326 or 3857) via `olcs.projection` source layer param.
- Call all getCapabilities with VERSION 1.3.0 to get layer available CRS
- Casade CRS definition in getCapabilities
> Import WMS

- geoportailv3/static/js/locationinfo/locationinfodirective.js
- package.json
The detection of layer projection is not really robust.
Fall back in ol-cesium to use map projection if no layer projection is defined.
Fix WMS layers like "Sentiers autopédestres" in 3D.
Also fix empty layer created on application loading.
> Fix 3D WMS

- geoportailv3/static/js/maincontroller.js
- geoportailv3/static/js/olcs/lux3dmanager.js
- geoportailv3/templates/index.html
- package.json
First shot first 3D tiles models integration.
Lux3DManager handle this, from mainController control. I prefer this than doing everything in mainController.
To have buildings aligned to terrain you need both parameters:
- &terrain_exaggeration=1
- &own_terrain
@gberaudo please review the approach.
I'm not sure if add angular constant in index.html is the best thing to do ?
For the ui, we propose to have a combo only in 3D mode under the background layer selector
Please make comments.
> Add 3D models support

- geoportailv3/static/js/maincontroller.js
- geoportailv3/static/js/olcs/lux3dmanager.js
See https://jira.camptocamp.com/browse/GSLUX-56 https://jira.camptocamp.com/browse/GSLUX-57 https://jira.camptocamp.com/browse/GSLUX-58
While testing, it looks like the own terrain does not work correctly:
- a tile is missing (see console log);
- the globe still looks flat even though the network window shows that terrain tiles are downloaded.
> Change default values and fix checkbox

- geoportailv3/static/less/offline.less
- geoportailv3/templates/index.html
GSLUX-89
Better CSS / other position for offline-warning message.
Before, it pushed all the page to the bottom (creates problems with the map and the footer)
Now, it looks like this (there is no more element to click on the top bar anyway):
> Fix CSS for offline message

- geoportailv3/static/js/appmodule.js
- geoportailv3/static/js/offline/defaultConfiguration.js
https://jira.camptocamp.com/browse/GSLUX-85
Define a custom offline configuration to specify behavior of layer downloading.
Find specs in https://jira.camptocamp.com/browse/GSLUX-83
```
When the menu is opened at a level < 11, it will zoom to level 11
When the menu is opened at a level > 15 it will zoom to level 15
The rectangle will take the current extent of the screen 
(minus a 10% buffer so that it can be greyed out)
If the current view contains a background map (member of group bglayers),
it should always be downloaded for the whole mapviewer extent from level 8-13
and further down according to the rules specified through the extent of 
the download area
```
> Add custom configuration for offline layers

- geoportailv3/static/js/offlineNgeoComponent.html
- geoportailv3/templates/index.html
- package.json
https://jira.camptocamp.com/browse/GSLUX-115
https://jira.camptocamp.com/browse/GSLUX-117
- When disconnecte but there is no offline data the activate link should not be shown
- One shouldn't be able to "Save new map" when disconnected
> Improve offline actions

- geoportailv3/static/js/offline/Configuration.js
- geoportailv3/templates/index.html
See https://jira.camptocamp.com/browse/GSLUX-120.
- use an hardcoded viewport extent to allow screen rotation;
- only download 4 zoom levels and change the zoomed zone to [12-15].
> Rework the extent computation

- geoportailv3/templates/geoportailv3.appcache
This fix the error in the Chrome console relative to allcategories retrieving:
> Fix appcache allcategories retrieving

- CONST_Makefile
@gberaudo Should I merge it into master ?
See: https://github.com/Kozea/CairoSVG/issues/232
Stack trace without this fix:
```
...
Collecting cairocffi (from CairoSVG==1.0.22->geoportailv3==1.0->-r CONST_requirements.txt (line 9))
Using cached https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 20, in <module>
File "/tmp/pip-build-vGk2u3/cairocffi/setup.py", line 7, in <module>
'cairocffi does not support Python 2.x anymore. '
RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.
----------------------------------------
Command "python …
```
> Update pip, CairoSVG doesn't build with pip 8

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
Save medium "fields" style at the same time when simple styles are changed to avoid desynchronization.
Initial use case was that changing simple style, while having medium style in local storage, was not saved and loaded when reloading the page and kept visible the old medium style instead. This is because the medium styles was not updated in the local storage and was keeping old version.
> Save medium styles when changing simple styles

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/layermanager.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/measure/MeasureController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/measure/measure.html
- geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
- geoportal/geoportailv3_geoportal/static-ngeo/less/navbars.less
- geoportal/package.json
Transition from HTML tooltips to ol styles.
The sketchStyle class ngeo methods to get measure, store it in feature property on `measureend`, & final style use it, because text in tooltip is not available anymore.
Feature is stored & readded to layer when active tool changes.
A `hidden` property is added to measure layer, which prevent it to be displayed in layer manager.
Needs [small ngeo tweak](https://github.com/camptocamp/ngeo/commit/b178a9e7451a4b660c728fedcf015e9f9854cd50).
(last minute check show me azimut isn't drawn in print… is `Circle` supported in MF print?)
> Render measure in print.

- config/print/print-apps/geoportailv3/a0_landscape.jrxml
- config/print/print-apps/geoportailv3/a0_portrait.jrxml
- config/print/print-apps/geoportailv3/a1_landscape.jrxml
- config/print/print-apps/geoportailv3/a1_portrait.jrxml
- config/print/print-apps/geoportailv3/a2_landscape.jrxml
- config/print/print-apps/geoportailv3/a2_portrait.jrxml
- config/print/print-apps/geoportailv3/a3_landscape.jrxml
- config/print/print-apps/geoportailv3/a3_portrait.jrxml
- config/print/print-apps/geoportailv3/a4_landscape.jrxml
- config/print/print-apps/geoportailv3/a4_portrait.jrxml
- config/print/print-apps/geoportailv3/config.yaml.tmpl
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/catalog/CatalogController.js
- geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
Alt + Shift modifiers by default. By passing a `shiftKeyRotate` query param, changes to Shift modifier only (to be tested on linux
systems).
Print templates have been updated to have north arrow:
> [c2cnextprod] Add support for map rotation

- geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
https://jira.camptocamp.com/browse/GSLUX-374
I changed the local storage behavior if there is already a expert or medium style saved. Now only the one active is saved there, the other is removed if existing. That insures that we can get only one as we launch the app without the permalink complete and can fill it with accurate local storage data without having two styles conflicting. This actually removes unused data from local storage.
> Serial is not initialized at launch if existing in local storage

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/views/userconfig.py
https://jira.camptocamp.com/browse/GSLUX-386
To test it, just load a simple style from permalink and see if the building has the same styling as the simple style applied from the editor interface.
Seems the python file had the key reverse between what is in the config, and what is in the json style file. Other than that, the fillExtrusions opacity was set to default (0.45) instead of 1. I had to add opacity to the building config, hopefully it does not seems there is other opacity values set somewhere for fills or lines elements, as it sets the same opacity for the full "building" config when parsed in the python.
> Fix building color with serialized config loading

- geoportal/geoportailv3_geoportal/admin/view/lux_predefined_wms.py
a bug has been observed since geoforms uses by default the name of the column for the CSS class. This results in a clash for the column 'label' of the table `lux_predefined_wms`
Before
After
> Fix style of admin page `predefined WMS`

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/backgroundselector/BackgroundselectorController.js
Sometimes previous variable is not set. 
In this case, hide each background layer to avoid a conflict with the new background.
> Be sure the old background is removed

- geoportal/jsapi/examples/iterate_layers_api.html
- geoportal/jsapi/examples/public_mymaps.html
- geoportal/jsapi/jsdoc/api/index.md
- geoportal/jsapi/src/map.js
- geoportal/jsapi/src/mymap.js
The PR makes various adaptions to in API doc to work with v4
- Fixes links on API doc home
- Should add example map on API doc home
- Includes `Map` and `MyMap` classes in doc
- Updates `public_mymaps.html` and `iterate_layers_api.hmtl` examples to use APIv4 (which will currently break the link to navigate back, as apiv4.geoportail.lu does not exist yet)
> Make API doc work with v4

- geoportal/geoportailv3_geoportal/static-ngeo/js/mymaps/MymapsController.js
PR removes `setDragHandler` from `MyMapsController`, which currently causes an error and does not seem to be necessary when testing and looking at: https://github.com/Geoportail-Luxembourg/geoportailv3/blob/integration/geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/message/modalComponent.js#L126
> Fix MyMapsController by removing setDragHandler method

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/map/map.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/map/mapDirective.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/module.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/offline/offlinebar.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/offline/offlinebar.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/offline/toggleOffline.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/offlineNgeoComponent.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/offlineWebComponent.ts
- geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
- geoportal/geoportailv3_geoportal/static-ngeo/less/layout.less
- geoportal/geoportailv3_geoportal/static-ngeo/less/offline.less
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.de.json
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.en.json
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.fr.json
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.lb.json
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/offline/component.js
The PR adds an offline toggle button (`offlinebar`) that opens toggle buttons for the existing ngeoOffline component and an offline web component to serve as a UI for the new "full offline" mode:
Todos:
> Offline UI

- geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js
- geoportal/geoportailv3_geoportal/static-ngeo/less/search.less
on small screens with a big number of results, items far down cannot be reached
the results list is therefore made scrollable (auto)
however in IOS, the viewport is not reduced by the keyboard overlay, so the whole screen may become scrollable
this seems to be a hard to fix undesirable feature of IOS
=> https://selleo.com/til/posts/l8xyxi1sao-preventing-body-scroll-for-modals-in-ios
=> https://stackoverflow.com/questions/37713970/ios-css-js-overlay-scroll-but-prevent-body-scroll
> fix search results in IOS

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline.component.ts
- geoportal/geoportailv3_geoportal/static-ngeo/js/offline/offlinebar.js
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/offline/component.js
PR only toggles one offline mode if the other one is inactive.
Note: This is necessary since `ng-click` seems to be triggered even though button is `disabled`.
> Offline: Fix buttons disabled status

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/offlineNgeoComponent.html
- geoportal/geoportailv3_geoportal/static-ngeo/less/offline.less
The ngeo-offline button was broken by https://github.com/Geoportail-Luxembourg/geoportailv3/commit/412f1eb0722a198d4a0aa9126f9ace5448a97f7c (which modified the button display for the native iOS app)
This PR should fix the 'arrow down' icon to be displayed in green (active) or red (inactive). The CSS `!important` is needed to overwrite the `ol-control` color, a class added in the iOS fix above.
To-do:
> Ngeo offline: Display button correctly

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/externaldata/externaldata.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/themeswitcher/ThemeswitcherController.js
- geoportal/geoportailv3_geoportal/static-ngeo/less/offline.less
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-617
Based on https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/49 PR integrates the `LayerPanel`, mainly handling state changes of `layersOpen` for the sidebar and `theme` for applying correct colors on legacy components and custom elements.
Todo:
Todos for separate PRs:
- integrate the remote layers element in a modal (along with layer metadata element)
- integrate the style selctors
> GSLUX-617: Integrate LayerPanel

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less
- geoportal/package.json
PR makes legacy vector editor work when new style editor button is clicked. Depends on: https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/60
> GSLUX-622: Style selector

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
PR inits sentry as it was the case before the vue integration. Now does not seem to throw errors in console anymore.
> GSLUX-627: Init sentry

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
https://jira.camptocamp.com/browse/GSLUX-550
PR sends `BackgroundAdded` event to piwik when `bgLayer` is changed in v4. All other piwik requests are still sent by v3.
> GSLUX-550: Log piwik events

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/package.json
This PR needs: https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/64
https://jira.camptocamp.com/browse/GSLUX-633
When clicking on theme button in the header, it should: 
- display the side panel (if not already displayed) and display the theme grid
- if the side panel is visible but the catalog tab is not selected, it should select the catalog tab and display the theme grid
- if the side panel and the theme grid are already visible, it should hide the side panel
> GSLUX-633: On click theme button in header

- geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/StateManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/resizemapDirective.js
- geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
- geoportal/package.json
Please test this PR with this v3 PR : https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/63
https://jira.camptocamp.com/browse/GSLUX-631
Background selection was not working as expected in v3.
- enable blank bg selection in v3 (bg `ZIndex` is now `-200` (instead of -1) like in v3 legacy
- handle special case: when **bg layer is blank** in permalink **and no layers** in permalink (was not working)
- added new component for alert notifications (when bg layer is blank in permalink and no layers in permalink, it now displays the message in an alert box, instead of display message with a `console.log`)
- added e2e tests
Some more stuffs:
- npm commands for building lib dev: disable minification in dev mode for debug purpose
- do not import main.css in ol.css, causing …
> GSLUX-631: Background selector KO

- geoportal/package.json
See
https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/68
https://jira.camptocamp.com/browse/GSLUX-620
Translation files (for all lang) need an update.
Some translations are missing, especially for new layers.
> GSLUX-620: Traductions manquantes pour les layers

- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/map/BackgroundLayerMgr.js
Instead of removing all legacy Bg managers (all occurences of ngeoBackgroundLayerMgr ), we map the v4 BG layer store inside the ngeo component.
This fixes all occurences of ngeoBackgroundLayerMgr.get
But the use of ngeoBackgroundLayerMgr.set has to be fixed case by case (for example in SearchController and Mymaps)
> use v4 store inside backgroundMgr service.

- geoportal/geoportailv3_geoportal/static-ngeo/js/print/PrintController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/print/Printservice.js
fix the print service by catching the custom URLs for MapLibreLayers
The correct bg layer is already obtained thanks to https://github.com/Geoportail-Luxembourg/geoportailv3/pull/3093
> Gslux 629 print

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
https://jira.camptocamp.com/browse/GSLUX-658
Right bottom button controls (offline mode, 3D, and info) were not visible in Firefox.
Now there are visible on Chrome, FF and Edge.
> GSLUX-658: Fix display bottom right btn controls for FF

- geoportal/geoportailv3_geoportal/static-ngeo/js/ExclusionManager.js
- geoportal/package.json
This PR needs https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/82
https://jira.camptocamp.com/browse/GSLUX-660
Display messages as notification instead of alert.
Test notification message with exclusions:
- Select Orthophoto 2013 and then Parcelles cadastrales
- or select Lot de chasse and Battues
> GSLUX-660: [Fix] unwanted alert msg

- geoportal/package.json
Linked to https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/87
https://jira.camptocamp.com/browse/GSLUX-659
> GSLUX-659: Display attributions

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
- geoportal/package.json
The goal of this PR is to integrate the new style selector. Use the new style selector with the remaining issues to be solved.
Current issue / to-dos: 
=> currently seems to cause permalink `bgLayer` not always updating if a customized style object is present (in permalink or localstorage)
=> also causes `setConfigForLayer_` error in console when reloading app after modifying style
- print after style modification works locally only when not using `vectortiles-print.geoportail.lu` here: https://github.com/Geoportail-Luxembourg/geoportailv3/blob/GSLUX-601-style-selector/geoportal/geoportailv3_geoportal/views/luxprintproxy.py#L226 (does not seem related to this PR)
> GSLUX-601: Integrate new style selector

- geoportal/CONST_Makefile
- geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/bootstrap.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/LuxRasterSynchronizer.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/print/Printservice.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/buildtools/webpack.prod.js
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/map/BackgroundLayerMgr.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-608
The goal of this PR is to allow activating the `UglifyJsPlugin`.
To do so, it:
- uses the legacy build from https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/103
- raises the memory limit for webpack
- gets rid of minification issues in `Themes.js` detected via `strictDi: true`
To-dos:
> GSLUX-608 Activate UglifyPlugin

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-698
Add init bg configs function, this initialization must be made AFTER vectortiles url initialization (this a a patch for v3)
> GSLUX-698: FIX init bg config AFTER urls init

- geoportal/geoportailv3_geoportal/static-ngeo/js/Mymaps.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/mymaps/MymapsController.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-701
- Add missing text "No layer selected" when user switches to offline mode
- in v4: update icons and add new scholl theme (after merging main onto integration-vue)
NB. This PR needs v4 fix : https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/117
> GSLUX-701: Missing text "No layer selected" when offline

- geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
This PR should allow opening permalinks in 3D mode correctly (eg. https://migration.geoportail.lu/theme/main?version=3&X=662398&Y=6360606&zoom=18&lang=fr&rotation=0&bgLayer=streets_jpeg&crosshair=false&layers=&opacities=&time=&streets_jpeg=&serial=&3d_layers=ACT2022_BD_L_BATI3D_LOD2%2CVDL2022_LOD2_IMPORT_old%2CBridges_LOD2%2CACT2019_LiDAR_Bridges_LOD1%2CACT2019_LiDAR_Vegetation&3d_enabled=true&3d_lon=5.95042&3d_lat=49.49531&3d_elevation=696&3d_heading=360.000&3d_pitch=-39.984).
For the fix, the `appLayerPermalinkManager.initBgLayers_()` which returned an empty Promise is not called anymore. The included logic of the function already does not seem to be used anymore and was thus not migrated further into v4. The part regarding the `tourisme` theme could not be reproduced on production, and …
> GSLUX-720: Fix reading permalink containing 3d_enabled

- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/offline/Downloader.js
This PR restricts offline mode to the thematic layers zoom levels if a thematic layer is present. In this case it does not include zooms for background layers on save in order to take the first and last zoom levels from the thematic layers when restoring via getItem('offline_content').
This seems a little like a workaround since this condition is not necessary on prod. 
That being said, the missing zoom restrictions actually also seem to be present on prod when using a thematic layer with the orthophotos as a baselayer.
> GSLUX-715: Restrict zoom in offline mode

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-718
- extract i18n from v4 into app._LANG_.json (combination of app._LANG.json from prod + i18n specific to v4, eg. aria labels, non existing v3 i18n)
- update legacy client._LANG_.json with prod version (removed specific v4 i18n from this file)
- passing i18next backend config (v3 url to cached fr.json) to lib lux
This PR needs https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/126
> GSLUX-718: Fix i18n (bis)

- geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js
This PR should fix:
- highlighting a cadastral parcel selected in the search
- adding layers from corresponding theme (cherry-picked from master and not tested locally)
- not removing cadastral parcel layer on a new cadastral search if one is already active
PR can be tested locally with tweak plugin for example using a `http://localhost:8080/fulltextsearch?query=8&limit=8` response from prod that includes a parcel.
> GSLUX-726: Highlight cadastral parcel on search

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
I believe this bug is related to the problem of bgLayer missing sometimes
This fix resolves a conflict in permalink update between v3 and v4 leading to js errors and incorrect styling.
Once trapped in a pad permalink / localstorage combination, bad things happen.
Unfortunately, it is again impossible to reproduce the reported bug, so we should merge the fix to check if evrything is going fine in the deployed app
> fix correct update of permalink

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/resizemapDirective.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-722
- Add new functionality to v4: embedded mode (just add param `?embedded=true` in url)
- Force resize map when embedded mode, with a timer for v3 (because of angular component, wait until they have finish rendering header and footer that will disappear, otherwise, there is an unwanted gutter). For v4, no timer needed.
- 
NB. This PR needs https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/125
> GSLUX-722: Fix embedded mode

- geoportal/geoportailv3_geoportal/static-ngeo/js/UserManager.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-749
This PR needs https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/165 from v4 to work.
> GSLUX-749: Use new v4 auth form component

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
- geoportal/package.json
PR integrates the `style-panel` replacing the `style-selector`.
To-do
Note that closing the `style-panel` in v3 still closes the sidebar as this is handled by the angular template. The evolution of keeping the sidebar open is only available in v4 app.
Note also that the "Vector tiles editor" translation is missing locally, but present on migration.
> GSLUX-639: Integrate style panel

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/draw/DrawController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/draw/FeaturePopupController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/draw/featurepopup.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/measure/MeasureController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/measure/measure.html
- geoportal/geoportailv3_geoportal/static-ngeo/js/profile/ProfileController.js
- geoportal/geoportailv3_geoportal/static-ngeo/ngeo/examples/elevationProfile.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-686
Use https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/169
> GSLUX-686: Profil component

- geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/routing/RoutingController.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/routing/routing.html
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-767
Use new v4 Profile Component in Routing.
PR to be used: https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/176
NB. Routing is not available  in dev, use chrome extension (eg. Tweak) to modify api responses. Also, units in dev does not correspond to production, you may again tweak de api response to get the real values (did not find a way to configure units in v3.
> GSLUX-767: Use new v4 profile component in routing

- geoportal/geoportailv3_geoportal/static-ngeo/js/draw/DrawnFeatures.js
- geoportal/geoportailv3_geoportal/static-ngeo/js/draw/FeatureHash.js
- geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-770
Use storage helper from v4 to update correctly features in url without removing newly added layers.
> GSLUX-770: Fix draw and layers in permalink v3

- geoportal/geoportailv3_geoportal/static-ngeo/js/query/QueryController.js
feature selection triggered a console error when clicking on OL controls.
=> Disable V3 handling for clicks on OL control buttons.
> Gslux 773 ol controls error
