Geoportail-Luxembourg/geoportailv3

CONST_Makefile, vars_geoportailv3.yaml
requires: https://github.com/camptocamp/c2cgeoportal/pull/1161#issuecomment-67154926
I put an arbitrary my_maps URL !
=> Make the db URL configurable

vars_geoportailv3.yaml
=> Set the right mymap URL

geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/maincontroller.js
This PR is a refactoring of the layer factory code. There are now more services. And the `appGetWmtsLayer` service is now used in the main controller to create the background layer. Later, the `appGetWmtsLayer` will be used by the background layer component.
Please review.
=> Layer factory refactoring

apache/geoportailv3.wsgi.mako, jkonnen.mk, main.mk, vars_main.yaml
this is a pull request with a questionmark.
to make the solution work in our wsgi environment, we have to define the proxy in the wsgi config.
I am not sure though if this has to be committed into master.
should this proxy setting be included in the makefile / vars-file rather than in the mako template directly?
=> mako template with proxy and logging settings

geoportailv3/templates/index.html, setup.py
=> Use 'desktop' as interface name

LUX_alembic/versions/46cb4ef6fd45_rest_url_has_to_be_hidden_move_it_from_.py, geoportailv3/models.py
un nouvel export de la base de données est nécessaire.
=> move rest_url from ui_metadata to lux_layer_internal_wms

geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/static/js/layermanager/layermanagerdirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html, less/geoportailv3.less, less/layermanager.less, less/theme.less, package.json
This a new PR for @pgiraud's `layer_manager` branch. For some reason @pgiraud's PR #142 didn't land into `master`, although the PR did have `master` as the target/base branch.
This is what I used to rebase the `layer_manager` onto the current `origin/master` branch:
```
$ git fetch origin
$ git checkout --no-track -b layer_manager origin/layer_manage  # create a local "layer_manager" branch off "origin/layer_manager"
$ git rebase --onto origin/master 77fe4a4  # 77fe4a4 is the first commit of "layer_manager" that I don't want (that is not part of Pierre's work)
$ git push --force origin layer_manager
```
And I then create that PR, using `master` as the "base" branch, and `layer_manager` as the "head" branch. I'm going to merge this. If it does not work, that means our GitHub repo is …
=> Add layer manager

LUX_alembic/versions/46cb4ef6fd45_rest_url_has_to_be_hidden_move_it_from_.py, geoportailv3/models.py
Because of bad git manipulations the commits added by #141 disappeared from master. This PR adds them back.
Git commands used:
```shell
$ git fetch origin
$ git checkout -b lux_db2 origin/lux_db
$ git rebase --onto origin/master 942c9f1
$ git push origin lux_db2
```
Please review one more time and merge.
=> move rest_url from ui_metadata to lux_layer_internal_wms (again)

geoportailv3/static/js/catalog/layertreenode.html, less/catalog.less, less/theme.less
With this pull request, we make use of the new `parentUid` and `depth` from ngeo to better manager accordion.
It also takes styling into account.
There may have some more work to done.
=> Better manage styling and behavior of catalog

geoportailv3/static/js/scalelinedirective.js
This is related to https://github.com/camptocamp/ngeo/pull/143.
=> Fix the scaleline directive

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/catalog/layertree.html, geoportailv3/static/js/catalog/layertreenode.html, geoportailv3/static/js/layerfactoryservice.js
This is to accommodate for the changes in https://github.com/camptocamp/ngeo/pull/140.
=> Use layer expr in catalog tree partial

CONST_Makefile
=> Rebuild config.yaml after make update-node-modules

geoportailv3/templates/index.html, less/layout.less
=> Fix issue with sidebar tabs label wrapping

geoportailv3/static/js/appmodule.js, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/layermanager/layermanagerdirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/scalelinedirective.js
As discussed with the Schweizmobil developer team his PR adds `@fileoverview` to each of our js files.
CC @fredj, @ochriste, @asaunier, @ger-benjamin.
=> Add file overviews to js files

vars_geoportailv3.yaml
added override of available_locale_names in geoportailv3 config, to add luxembourgish !
=> added luxembourgish to locale names

development.ini.in
=> Readding missing pyramid_closure settings

development.ini.in, geoportailv3/lib/search.py, geoportailv3/utils/db2es.py, geoportailv3/utils/db_to_es.py, geoportailv3/views/fulltextsearch.py, setup.py, vars_geoportailv3.yaml, vars_wepa.yaml
Left out the .po changes, that were introduced accidentally
=> Search (refactored pull request)

CONST_Makefile, geoportailv3/templates/index.html, tasks/build.js
=> Concat minified js files into one file

.gitignore
=> Add .eggs to gitignore

geoportailv3/static/js/backgroundlayer/backgroundlayer.html
See https://github.com/camptocamp/ngeo/pull/152.
=> Remove unnecessary watchers

geoportailv3/static/js/catalog/layertreenode.html, geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/templates/index.html
=> Translations for catalog and layermanager

geoportailv3/scripts/db2es.py, setup.py
=> moved db2es to scripts folder, and added as a script command

geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/icons.less, geoportailv3/static/less/layout.less
=> fix issues #203 and #207

geoportailv3/static/js/catalog/layertreenode.html, geoportailv3/static/js/layerinfo/layerinfo.html, geoportailv3/static/js/layerinfo/layerinfodirective.js, geoportailv3/static/js/layerinfo/layerinfoservice.js, geoportailv3/static/js/layerinfo/popup.html, geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/static/js/main.js, geoportailv3/static/less/icons.less, geoportailv3/templates/index.html
For now, it doesn't do much but displays an almost empty popup when clicking on the "info" button in both catalog and layer manager.
It should eventually call a service to get metadata info.
Please review.
=> Layerinfo directive & service

geoportailv3/static/less/layout.less
=> Map is 100% in full screen mode

geoportailv3/static/less/icons.less, geoportailv3/static/less/navbars.less, geoportailv3/static/less/theme.less
partially adresses #243 . 
@pgiraud I cant seem to be able to fix gaps between tiles for language switcher menu , can you help ?
=> language switcher styling

geoportailv3/static/less/geoportailv3.less
=> Fixing font awesome path

geoportailv3/templates/index.html
We don't need to translate the string in the language switcher.
Please review.
=> Removed unrequired translate

development.ini.in, geoportailv3.mk, geoportailv3/__init__.py, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/usercontroller.js, geoportailv3/static/less/icons.less, geoportailv3/static/less/layout.less, geoportailv3/static/less/navbars.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html, geoportailv3/views/authentication.py, production.ini.in, setup.py, vars_geoportailv3.yaml
Please review. 
1) Some new parameters have to be added in config such as ldap_url ldap_bind ldap_passwd ldap_base_dn
Up to now these parameters are in my vars_renaud_yaml. I'm not sure if I have to add it anywhere else.
If these parameters are not set, Travis failed. 
2) library for openldap-devel has to be installed.
=> authentication

vars_geoportailv3.yaml
only left Infobar UI to implement
=> Elevation Web Service working

geoportailv3/static/js/catalog/layertreenode.html
=> one-time binding cannot be used in combination w/ translate filter

geoportailv3/static/js/layerinfo/layerinfoservice.js
This is to accommodate [changes](https://github.com/camptocamp/ngeo/pull/168) to ngeo.
=> Change popup.open to popup.setOpen

CONST_Makefile, geoportailv3/static/js/layerinfo/layerinfodirective.js, geoportailv3/static/js/layerinfo/layerinfoservice.js, geoportailv3/static/js/usercontroller.js
This PR fixes a typo in `CONST_Makefile` and lint errors in js files.
Fixes #268.
=> Re-add js lint and fix lint errors

CONST_requirements.txt
=> Fix pyramid revision

README.rst, geoportailv3/static/js/usercontroller.js
This PR makes minor changes to the JS code. It also adds libldap2-dev and libsasl2-dev as requirements in the README file (I don't know how the equivalent RedHat packages are named).
=> Misc changes

CONST_vars.yaml, geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html
This PR aims to fix the javascript debug mode that was broken by the update to the latest c2cgeoportal version.
Depends on camptocamp/pyramid_closure#50, which should be merged first.
=> Change pyramid_closure config for camptocamp/pyramid_closure#50

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/layerinfo/layerinfoservice.js, geoportailv3/static/js/layerinfo/popup.html, geoportailv3/static/less/layout.less
=> Display in a popup the information about metadata and the legend coming from wiki

build.json, geoportailv3/static/js/main.js, geoportailv3/static/js/measure/measure.html, geoportailv3/static/js/measure/measurecontroller.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/icons.less, geoportailv3/static/less/navbars.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
Adds tools to measure length, area, and azimut.
=> Measure tools

geoportailv3/static/js/infobar/elevationdirective.js, geoportailv3/templates/index.html
=> Fix url routes for services

geoportailv3/__init__.py, geoportailv3/views/qr.py, setup.py
controller for generating qrcodes for geoportail urls
=> added a controller for generating qrcodes

geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/static/js/layermanager/layermanagerdirective.js, geoportailv3/static/js/maincontroller.js
~~Only working in debug mode, help appreciated~~ see comment
=> Selected Layers reorder using drag & drop

geoportailv3/static/js/infobar/scaleselectordirective.js, geoportailv3/static/js/maincontroller.js
=> Set Zoom & Extent Limits

CONST_Makefile
This PR addresses the issue raised in https://github.com/Geoportail-Luxembourg/geoportailv3/pull/336#issuecomment-78240539.
=> Rebuild template cache when directive partials change

geoportailv3/static/js/infobar/infobardirective.js
=> Remove extra require to ol.control.MousePostion

geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/static/less/layermanager.less
Commit message says it all.
Depends on: https://github.com/camptocamp/ngeo/pull/195
Fixes #343
=> Better style for dragged element in layermanager

CONST_requirements.txt
This will need to be done in the update scaffold of c2cgeoportal as well.
=> Update pyramid closure

geoportailv3/static/js/infobar/scaleselector.html
=> Fix ordering in scale selector

geoportailv3/static/js/backgroundlayer/backgroundlayer.html, geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js, geoportailv3/static/js/backgroundlayer/blanklayerservice.js, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/exclusionmanagerservice.js, geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/notifyservice.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/notify.less
I now have something working for the layer exclusions.
The last that needs to be addressed is the translations of the messages.
=> Pgiraud layers exclusion

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/catalog/layertree.html, geoportailv3/static/js/catalog/layertreenode.html, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/themeswitcher/themes.html, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/static/less/layout.less, geoportailv3/static/less/sidebar.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
=> Theme switcher

geoportailv3/static/js/measure/measuredirective.js
Remarks from one of our tester regarding the whole azimuth control :  
title for distance and azimuth would be helpful 
a line from center to north would be helpful too.
Please review.
=> Show elevation offset in azimuth control

geoportailv3/views/wms.py
=> Solves escape parameter problems

geoportailv3/static/js/profile/profiledirective.js
=> Show same value on map and chart when hovering chart

geoportailv3/static/js/exclusionmanagerservice.js
Please review.
@jaykayone I'm not sure the messages are clear enough. The messages could probably be shorter and more explicit.
Also though this exclusion notification mechanism improves usability, I'm still not sure users understand immediately what happens. At least, they are notified.
=> Layer exclusions updates (translation and layer removal)

geoportailv3/static/less/catalog.less, geoportailv3/static/less/theme.less
With this pull request the colors are configured more manually but the result is better.
=> Theme colors

main.mk
=> Remove trailing whitespace

.gitignore, CONST_CHANGELOG.txt, CONST_Makefile, CONST_dev-requirements.txt, CONST_vars.yaml, CONST_versions.txt, geoportailv3/forms.py, geoportailv3/locale/en/LC_MESSAGES/geoportailv3-server.po, geoportailv3/models.py, geoportailv3/subscribers.py, print/WEB-INF/classes/logback.xml.mako, print/WEB-INF/classes/mapfish-spring-application-context-override.xml, setup.py, travis.mk
La localisation côté serveur doit aussi être corrigée ...
=> Upgrade to GeoMapFish master

geoportailv3/static/less/layout.less
=> Hide elements in sidebar at first

build.json
This PR fixes the OpenLayers externs in our build configuration file.
=> Fix the OpenLayers externs

geoportailv3/static/js/main.js, geoportailv3/static/js/print/print.html, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/icons.less, geoportailv3/static/less/navbars.less, geoportailv3/static/less/print.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
With this pull request, I add a new directive with its template.
=> Print directive

geoportailv3/static/less/layout.less
=> Use white bg for map

geoportailv3/static/js/authentication/authenticationdirective.js, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/templates/index.html
The objective of this PR is to reload themes after the user has logged in or logged out. This is still WIP for now.
Fixes #389.
=> Reload themes after authentication

geoportailv3/static/js/backgroundlayer/backgroundlayer.html
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/428.
Please review.
=> Update background layer labels when switching lang

geoportailv3/static/less/theme.less
Fixes #444.
To test it, open the developer tools and remove the value for the `data-theme` attribute in `body` tag.
=> Adding default (or invalid) theme colors

geoportailv3/static/js/print/printdirective.js
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/468.
Please review.
=> Add support for A2, A1, and A0 print-outs

geoportailv3/static/less/icons.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
=> Adding a theme icon in the top bar

geoportailv3/static/js/authentication/authentication.html, geoportailv3/static/less/layout.less, geoportailv3/static/less/theme.less
=> Fix layout and element visibility in login panel

geoportailv3/static/less/theme.less
Something went wrong with the merge commit for #454.
https://github.com/Geoportail-Luxembourg/geoportailv3/commit/15e2bef1799f9aabc2df7124ca275f2b57131035
=> Theme icon fix

geoportailv3/static/less/icons.less, geoportailv3/templates/index.html
=> Change theme icon position

geoportailv3/static/js/print/print.html, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/less/icons.less
=> Adding a 'printing' notification for user

geoportailv3/static/less/layout.less, geoportailv3/static/less/theme.less
=> Fix regression of theme switcher colors

geoportailv3/static/js/search/search.html, geoportailv3/static/less/search.less
=> Put magnifier icon in the search field

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/templates/index.html
As requested by @jaykayone , users can enter LUREF coordinates in search field to go to specified location
fixes #492
=> Search for Coordinates

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/templates/index.html
Using ol.proj in index.html produced errors 
This reverts commit 343db2e2903408407046a696e7092851dd060806.
=> Bugfix - Revert maxExtent to a constant 

geoportailv3/static/js/locationcontrol.js
=> set geolocation options

geoportailv3/static/js/interrogation/interrogationdirective.js, geoportailv3/static/js/layerfactoryservice.js
=> cors header

geoportailv3/static/js/authentication/authentication.html, geoportailv3/static/js/authentication/authenticationdirective.js, geoportailv3/templates/index.html
=> add links to myaccount with language support

geoportailv3/static/js/print/printdirective.js
=> Set print DPI 300 for nicer printed maps

package.json
=> Fix OL3 version to prevent errors due to FeatureOverlay deprecation

package.json
This mitigates the problem reported in https://github.com/Geoportail-Luxembourg/geoportailv3/issues/522 but doesn't fix it completely.
=> Update angular-gettext to 2.1.0

geoportailv3/static/less/theme.less
=> white header bar

geoportailv3/static/js/search/searchdirective.js
=> Change jQuery.event to jQuery.Event

geoportailv3/__init__.py, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/templates/index.html, geoportailv3/views/luxthemes.py
=> Lux protected themes

CONST_CHANGELOG.txt, CONST_dev-requirements.txt, CONST_requirements.txt, CONST_requirements_windows.txt, CONST_vars.yaml, CONST_versions.txt, geoportailv3/locale/de/LC_MESSAGES/geoportailv3-server.po, geoportailv3/locale/en/LC_MESSAGES/geoportailv3-server.po, geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-server.po, geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-server.po, setup.py
fix #561
Know issue: the link shortner don't work he will be fixed in the next version
=> Upgrade to GeoMapFish 1.6.0rc1

geoportailv3/static/js/appmodule.js, geoportailv3/static/less/theme.less
=> Don't use :hover on mobile devices

geoportailv3/static/js/coordinatestringservice.js, geoportailv3/static/js/elevationservice.js, geoportailv3/static/js/infobar/elevationdirective.js, geoportailv3/static/js/infobar/projectionselectordirective.js, geoportailv3/static/js/locationinfo/locationinfo.html, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/info.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/shorturlservice.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/sidebar.less, geoportailv3/templates/index.html, vars_wepa.yaml
=> Right-click info

geoportailv3.mk, geoportailv3/static/js/layerfactoryservice.js, geoportailv3/templates/index.html, vars_geoportailv3.yaml
fix #520 
Add the following entry in the local yaml file to use another proxy: 
```proxy_wms_url: http://devv3.geoportail.lu/main/wsgi/wms```
Could you please review.
=> get proxy url from config file

geoportailv3/static/js/profile/profiledirective.js
See the commit message for details.
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/530.
=> Use $digest instead of $apply in profile directive

geoportailv3/static/js/infobar/infobar.html, geoportailv3/static/less/icons.less
=> Infobar button to use icons font

geoportailv3/static/js/measure/measuredirective.js
=> Measure help message are now translatable

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/templates/index.html
=> no query info when measurement tools are opened

geoportailv3/static/js/query/querydirective.js, geoportailv3/views/getfeatureinfo.py
@jaykayone @petzlux Could you please check if the click tolerance is better now ?
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=15&X=656759&Y=6407164&crosshair=true
=> big tolerance for point small tolerance for others geometries

geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/search/searchdirective.js
=> clear highlight when a layer is added

geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html
adding missing permalink variables:
=> Permalink variables

geoportailv3/views/luxprintproxy.py
=> Update the print legend to suport new version of c2cgeoportal

geoportailv3/static/js/authentication/authenticationdirective.js
=> use GET method with logout

geoportailv3/static/js/layerpermalinkservice.js
=> check if layer and opacities exists , and not duplicate, before adding

geoportailv3/locale/de/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/en/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-client.po, geoportailv3/static/js/search/search.html, geoportailv3/templates/index.html
=> set translate keys visible at load to french, update translations

geoportailv3/static/js/query/mymaps.html
=> test if image exists

geoportailv3/static/js/query/querydirective.js
=> uses only the visible layers

geoportailv3/__init__.py
=> rename wms route

geoportailv3/locale/de/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/en/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-client.po, geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-client.po, geoportailv3/static/js/print/printdirective.js
=> add print sizes labels to translate strings, add translations

geoportailv3/static/less/layout.less, geoportailv3/static/less/navbars.less
=> no scrollbar

geoportailv3/static/js/locationinfo/locationinfodirective.js
=> remove test for TouchEvent

geoportailv3/static/js/infobar/scaleselectordirective.js
fix #569 - better scale selector values
=> Better scalebar value

geoportailv3/static/js/print/print.html, geoportailv3/static/js/print/printdirective.js, geoportailv3/templates/index.html
=> Adding real legends in printing

geoportailv3/static/js/search/searchdirective.js
=> change fitgeometry to fit

geoportailv3/static/js/query/querydirective.js
=> open info window only if results close info window if no result

CONST_Makefile
Will be back-ported to c2cgeoportal
=> Be able to add project specific libs

CONST_Makefile
Add missing touch
Will be back-ported to c2cgeoportal
=> Rebuild after an update

geoportailv3/static/js/locationinfo/locationinfodirective.js
#653 needs to be merged first.
I had a lot of troubles fixing this one with the help of @elemoine.
To summarize, we need to wait for ngAnimate to be "ready" before we can put observers on animations.
But we also had troubles with weird behavior in Angular which we haven't fully understood.
=> Pgiraud crosshair map distortion

geoportailv3/static/js/print/print.html, geoportailv3/static/less/navbars.less
=> Pgiraud print form

geoportailv3/static/js/locationinfo/locationinfodirective.js
=> Fix location info issues

geoportailv3/static/js/search/searchdirective.js
fix #660  and also search not working properly after language change
=> Petzlux search bglayer fix

geoportailv3/static/js/layerpermalinkservice.js
addressing @elemoine code comments
=> add missing goog.require in layerpermalink

geoportailv3/static/js/print/printdirective.js
=> add scalebar attribute

geoportailv3/static/js/print/printdirective.js
Fixes https://github.com/Geoportail-Luxembourg/geoportailv3/issues/682.
=> Pass current lang to print service

geoportailv3/static/js/search/searchdirective.js
=> Search for Easting Northing coordinates in several formats

geoportailv3/static/less/sidebar.less
=> Fix layers scrollbar

geoportailv3/static/less/sidebar.less
=> Fix ie getinfo scrollbar

geoportailv3/views/authentication.py
=> set a default value for email field

geoportailv3/views/getfeatureinfo.py
This closed #713 
Thanks @jaykayone
=> bad spatial filter

geoportailv3/static/js/query/querydirective.js
=> change cursor and perform query only one the previous one has finished

geoportailv3/static/js/layerinfo/layerinfoservice.js, geoportailv3/static/js/layerinfo/popup.html
=> trust the description

geoportailv3/static/js/coordinatestringservice.js, geoportailv3/static/js/locationinfo/locationinfo.html, geoportailv3/static/less/layout.less, geoportailv3/static/less/sidebar.less
=> DMS Coordinates output - add one decimal

geoportailv3/static/less/sidebar.less, geoportailv3/static/less/theme.less
Could you please test the layer slider on different devices ?
=> custom range slider and better alignment

geoportailv3/static/js/query/querydirective.js
=> reset the info panel with an empty value to init the scrollbar

geoportailv3/static/js/print/printdirective.js
This PR changes the print directive to send a cancel request to the print service when the user hits the "abort" link.
This does not work for the moment, because I get 404 from MapFish Print when attempting to cancel a report:
```
2015-06-22 11:44:26,464 INFO  [c2cgeoportal.views.proxy][Dummy-4] Send query to URL:
http://localhost:8080/print-elemoine/print/geoportailv3/cancel/cd3020f7-a6e5-4665-a24d-b2767d001ef4@9a0c91e4-95ae-4495-9cf7-8378f802ab7f?.
2015-06-22 11:44:26,468 ERROR [c2cgeoportal.views.proxy][Dummy-4] Error 'Not Found' in response of URL:
http://localhost:8080/print-elemoine/print/geoportailv3/cancel/cd3020f7-a6e5-4665-a24d-b2767d001ef4@9a0c91e4-95ae-4495-9cf7-8378f802ab7f?.
2015-06-22 11:44:26,468 ERROR [c2cgeoportal.views.proxy][Dummy-4] Status: 404
2015-06-22 11:44:26,468 …
```
=> Send cancel requests to MapFish Print service

geoportailv3/static/js/layermanager/layermanager.html, geoportailv3/static/less/layermanager.less
could you please check on mobile devices ?
=> clickable title and delete button

CONST_Makefile, build.json, geoportailv3.mk, geoportailv3/externs/fuse.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/templates/index.html, package.json
Add fuzzy search for layers and basemap layers.
This makes use of an external library [Fuse.js](https://github.com/krisk/Fuse) . I have written an externs file for the library.
=> Fuzzy layer search

.gitignore, .tx/config, CONST_Makefile, geoportailv3.mk, geoportailv3/locale/de/LC_MESSAGES/geoportailv3-tooltips.po, geoportailv3/locale/en/LC_MESSAGES/geoportailv3-tooltips.po, geoportailv3/locale/fr/LC_MESSAGES/geoportailv3-tooltips.po, geoportailv3/locale/lb/LC_MESSAGES/geoportailv3-tooltips.po, geoportailv3/scripts/tooltips2pot.py, geoportailv3/templates/index.html, geoportailv3/views/getfeatureinfo.py, setup.py
@petzlux Could you please review ?
=> tools to create the translation keys for tooltips

geoportailv3/static/js/print/printdirective.js
=> check if custom print scales exists and is not empty

geoportailv3/static/js/share/share.html, geoportailv3/static/js/share/sharedirective.js
=> fix facebook sharing

geoportailv3.mk
@jaykayone could you please review and tell me if it works as you expect ?
=> always create the tooltips pot file

geoportailv3/views/fulltextsearch.py
=> Reduced false positives through separate fuzzy query

geoportailv3/views/getfeatureinfo.py
Seems to work with data from ANF
=> suport multipolygon from arcgis

geoportailv3/static/js/authentication/authenticationdirective.js, geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/infobar/elevationdirective.js, geoportailv3/static/js/infobar/infobardirective.js, geoportailv3/static/js/infobar/projectionselectordirective.js, geoportailv3/static/js/infobar/scalelinedirective.js, geoportailv3/static/js/infobar/scaleselectordirective.js, geoportailv3/static/js/layerinfo/layerinfodirective.js, geoportailv3/static/js/layermanager/layermanagerdirective.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/map/mapdirective.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/js/profile/profiledirective.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/static/js/share/sharedirective.js, geoportailv3/static/js/share/shorturldirective.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js
This is required by recent versions of the compiler.
=> Add goog.provide's for constructors

.gitignore
I just built the project and got "not staged changes" ready to commit on ".po" files.
I think they need to be ignored.
Please review.
=> Ignore the generated *-client.po files

CONST_Makefile, build.json, geoportailv3/templates/index.html
See commit message for details.
Fixes #826.
=> Use template cache also in debug mode

geoportailv3/static/js/main.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/templates/index.html
Before we go further with the mymaps features implementation, we need a directive.
With this code, I add an almost empty directive.
Please review.
=> Base code for the mymaps directive

pgiraud.mk
@elemoine Do you want me to add the same in your .mk file?
=> Adding a watcher for templates

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js
With this pull request we get the base code to manage maps.
It includes the base code to show the "open a map" as well as the "modify" modal windows.
This of course simulates a lot of things for now. For example, it considers that the user is authenticated.
Once this pull request is merged, I'll work on the styling a bit more.
=> Base UI code for managing mymaps creation and modification

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/mymaps.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
This pull request adds some styling to the first elements added to mymaps.
More UI work will of course be done as soon as new elements are added.
Please review.
=> Mymaps styling

geoportailv3/static/js/query/pcn_pag.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/less/sidebar.less, geoportailv3/static/less/theme.less, geoportailv3/views/getfeatureinfo.py
@jaykayone Is it working as expected ? 
Maybe could we use the same mechanism to order one cadastral extract for multiple parcels.
Please review.
=> Lux muliselection

geoportailv3/static/js/draw/draw.html, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/less/icons.less, geoportailv3/static/less/mymaps.less, geoportailv3/static/less/navbars.less, geoportailv3/templates/index.html
Features are added to the feature overlay, and are listed in the mymaps bar.
=> [WIP] Adding support for drawing tools

build.json, geoportailv3/externs/typeahead.js, geoportailv3/static/js/search/creategeojsonbloodhound.js, geoportailv3/static/js/search/searchdirective.js
This PR should fix the remaining search problems we have.
@rmichaelis, can you please test this?
=> Use our own CreateGeoJSONBloodhound factory

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/less/layermanager.less, geoportailv3/static/less/mymaps.less, geoportailv3/static/less/theme.less, geoportailv3/static/less/variables.less, geoportailv3/templates/index.html
With some more general styling.
Please review.
=> Show an example of actions items in dropdown menu

geoportailv3/static/js/print/printdirective.js
This PR aims to address #759. This is WIP for the moment.
=> Change map zoom when changing print scale

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js
=> Renaud mymaps menu

geoportailv3/__init__.py, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/views/mymaps.py
=> Renaud copy map

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/views/authentication.py, geoportailv3/views/mymaps.py
to be rebased once @rmichaelis merges https://github.com/Geoportail-Luxembourg/geoportailv3/pull/879
=> Mymaps Categories

geoportailv3/static/js/mymaps/mymaps.html
See https://github.com/camptocamp/ngeo/pull/372
=> Ngeo modal now relies on ngModelController

geoportailv3/__init__.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/views/mymaps.py
=> Renaud 2 lists

geoportailv3/mymaps.py
=> In case of a null value it returns a default value

geoportailv3/static/js/mymaps/mymaps.html
=> ngModel is now required

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/views/mymaps.py
@elemoine This code should work, but when I open the Modal, i get an error: 
````
TypeError: shownSet is not a function
at modal.js:66
at Scope.$eval (angular.js:15830)
at Scope.$apply (angular.js:15929)
at HTMLDivElement.<anonymous> (modal.js:65)
at HTMLDivElement.jQuery.event.dispatch (jquery.js:4670)
at HTMLDivElement.elemData.handle (jquery.js:4338)
at Object.jQuery.event.trigger (jquery.js:4579)
at HTMLDivElement.<anonymous> (jquery.js:5289)
at Function.jQuery.extend.each (jquery.js:384)
at jQuery.fn.jQuery.each (jquery.js:136)
````
Is this connected to how the `ngeo-modal-shown` angular expression is evaluated? 
fix #888
=> Petzlux create map

geoportailv3/mymaps.py, geoportailv3/static/js/draw/draw.html, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/styleediting.js, geoportailv3/static/js/mymapsservice.js
=> Drawing Text labels

geoportailv3/templates/index.html
=> remove double loading of proj4

build.json
fix #946  - ngeo update breaks build
=> Fix Ngeo update breaks build

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/less/mymaps.less, geoportailv3/static/less/theme.less
With this pull request, I tried to improve the design of the mymaps block a bit.
Please review.
=> Mymaps design polishing

geoportailv3/static/js/draw/drawnfeaturesservice.js
=> Correct attribute name for label

geoportailv3/static/js/draw/drawdirective.js
=> Mymaps improved element naming

geoportailv3/static/js/draw/drawdirective.js
=> measure while drawing

geoportailv3/static/js/mymaps/mymapsdirective.js
=> Fix - Choose Map when no Map is owned by User

geoportailv3/static/js/draw/drawdirective.js
=> Move selected geometry to new position

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/styleediting.js, geoportailv3/static/js/draw/symbolselector.html, geoportailv3/static/js/draw/symbolselector.js, geoportailv3/static/js/imageupload/imguploaddirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/less/featurepopup.less, geoportailv3/templates/index.html, geoportailv3/views/mymaps.py, scripts/sync_ms.sh
@jaykayone could you please have a look here : http://devv3.geoportail.lu/renaud/
=> upload symbol & thumbnail for feature

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/js/themeservice.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/themeswitcher/themes.html, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/templates/index.html
Could you please review and at least check 
1) The interraction between the url parameters and mymaps.
2) Already existing layers when a new map is opened.
3) Could someone propose a better icon when layers change.
Testing env here http://devv3.geoportail.lu/renaud
=> Mymaps layers

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/share/shorturl.html, geoportailv3/static/js/share/shorturldirective.js
=> Fix save feature

geoportailv3/static/js/mymaps/mymaps.html
fix #949 reword public map checkbox
=> Reword public map checkbox

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/less/mymaps.less, geoportailv3/templates/index.html, geoportailv3/views/mymaps.py
Could you please review.
I've added the missing echo service (exportgpxkml).
This service will be removed when c2cgeoportal will be updated.
=> import/export gpx/kml

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js
=> reset mymaps

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupservice.js, geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/symbolselector.html, geoportailv3/static/less/featurepopup.less
=> Popup is now draggable

geoportailv3/static/js/draw/drawdirective.js
=> tranlation only when the geometry is editable

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js
=> delete a specific mymaps

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/templates/index.html
=> keep mymaps panel opened when user draws something

geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/less/featurepopup.less, geoportailv3/static/less/theme.less
=> better slider styling

geoportailv3/static/js/mymaps/mymapsdirective.js
=> save layers before reloading map information

geoportailv3/static/js/mymaps/mymaps.html
=> Auto select the title and description

geoportailv3/static/js/layerinfo/popup.html
=> Greater than interpreted as end tag

geoportailv3/mymaps.py, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/less/mymaps.less
=> sort MyMaps Maps by date

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/featurepopupservice.js, geoportailv3/static/js/mymaps/mymapsdirective.js
@petzlux could you please review ?
=> export the feature as GPX and KML

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/symbolselector.html, geoportailv3/static/less/featurepopup.less
=> style the file browser buttons

geoportailv3.mk
=> Excludes node_modules.

geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/styleediting.js, geoportailv3/static/js/draw/symbolselector.html, geoportailv3/static/js/draw/symbolselector.js, geoportailv3/static/less/featurepopup.less, geoportailv3/templates/index.html
=> Use html5 color picker.

geoportailv3/static/js/draw/drawnfeaturesservice.js
=> Use a unique short name

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/measure.js, geoportailv3/static/js/draw/measureLength.js
=> Fix continue line

geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/styleediting.js, geoportailv3/static/js/mymapsservice.js
=> Show line direction

geoportailv3/static/js/draw/drawdirective.js
=> Delete vertice using SHIFT key

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/featurepopupservice.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/profileservice.js, geoportailv3/static/less/featurepopup.less, geoportailv3/templates/index.html
fix #783 
(Need to wait for #791 Export KML & #932 )
=> Mymaps Objects information

geoportailv3/mymaps.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/featurepopupservice.js, geoportailv3/static/js/draw/measure.js, geoportailv3/static/js/draw/modifycircleinteraction.js
=> Fix circle3

geoportailv3/static/js/appmodule.js, geoportailv3/static/js/backgroundlayer/backgroundlayerdirective.js, geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/featurepopupservice.js, geoportailv3/static/js/draw/measure.js, geoportailv3/static/js/draw/modifycircleinteraction.js, geoportailv3/static/js/exclusionmanagerservice.js, geoportailv3/static/js/layeropacitymanagerservice.js, geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/locationcontrol.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/js/profile/profiledirective.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, package.json
=> Migrate from goog.events to ol.events

geoportailv3/templates/index.html
=> Add missing quotes

geoportailv3/__init__.py, geoportailv3/geocode.py, geoportailv3/static/js/geocodingservice.js, geoportailv3/static/js/locationinfo/locationinfo.html, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/templates/index.html, geoportailv3/views/geocode.py
=> Find and display the nearest address on right mouse click

geoportailv3/__init__.py, geoportailv3/static/js/profile/profile.html, geoportailv3/static/js/profile/profiledirective.js, geoportailv3/static/less/layout.less, geoportailv3/templates/index.html, geoportailv3/views/profile.py
=> Export measured profile as a csv file.

geoportailv3/views/getfeatureinfo.py
=> Compute length only for LineString

geoportailv3/static/js/query/ont_poi.html
=> Add a template for ont

package.json
=> Migrate to angular 1.5.0

geoportailv3/views/luxprintproxy.py
=> Change default pdf name

geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/profileservice.js, geoportailv3/static/js/query/mymaps.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/less/sidebar.less, geoportailv3/views/profile.py
=> Profile in mymaps public layers

geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html
=> Do not automatically open info panel on xs screen

geoportailv3/models.py, geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/views/getfeatureinfo.py
=> Mire order default gfi

geoportailv3/models.py, geoportailv3/static/js/deviceservice.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/query/aero.html, geoportailv3/static/js/query/affaires.html, geoportailv3/static/js/query/batiments.html, geoportailv3/static/js/query/bus.html, geoportailv3/static/js/query/cfl_hecto.html, geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/flik.html, geoportailv3/static/js/query/inst_pub.html, geoportailv3/static/js/query/meteo.html, geoportailv3/static/js/query/mo.html, geoportailv3/static/js/query/mymaps.html, geoportailv3/static/js/query/ng95.html, geoportailv3/static/js/query/ont_poi.html, geoportailv3/static/js/query/parcels.html, geoportailv3/static/js/query/parcels_go.html, geoportailv3/static/js/query/pcn_pag.html, geoportailv3/static/js/query/poi.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/query/urplang.html, geoportailv3/static/js/query/viti_flik.html, geoportailv3/static/js/query/viti_kleinlage.html, geoportailv3/static/js/query/viti_name.html, geoportailv3/static/js/query/viti_parcels.html, geoportailv3/templates/index.html, geoportailv3/views/getfeatureinfo.py
=> Mire link object

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js
=> Ask a confirmation before deleting something

geoportailv3/static/js/print/printdirective.js
=> Close the feature edition popup before printing

geoportailv3/mymaps.py
=> backward compatibility with v2

geoportailv3/static/js/maincontroller.js
=> Load tiles during animation

geoportailv3/static/js/print/printdirective.js
=> Landscape first

geoportailv3/static/js/authentication/authenticationdirective.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/templates/index.html
=> Close user popup when connected

geoportailv3/static/js/query/default.html, geoportailv3/views/getfeatureinfo.py
=> Fix link to object

geoportailv3/static/js/layerpermalinkservice.js
=> Get initial layers only during app initialization

geoportailv3/static/js/draw/featurepopup.html
=> Some components can be shown even if the feature is not editable

geoportailv3/static/js/profile/profile.html, geoportailv3/static/js/profile/profiledirective.js
=> Display elevation gain and loss

geoportailv3/static/js/statemanagerservice.js
=> Load layers from local storage when sharing an object

geoportailv3/static/js/query/mymaps.html, geoportailv3/static/js/query/querydirective.js
=> Fix the image path

print/print-apps/geoportailv3/a0_landscape.jrxml, print/print-apps/geoportailv3/a0_portrait.jrxml, print/print-apps/geoportailv3/a1_landscape.jrxml, print/print-apps/geoportailv3/a1_portrait.jrxml, print/print-apps/geoportailv3/a2_landscape.jrxml, print/print-apps/geoportailv3/a2_portrait.jrxml, print/print-apps/geoportailv3/a3_landscape.jrxml, print/print-apps/geoportailv3/a3_portrait.jrxml, print/print-apps/geoportailv3/a4_landscape.jrxml, print/print-apps/geoportailv3/a4_portrait.jrxml
=> new print templates

geoportailv3/static/js/layerpermalinkservice.js
=> Starting bglayer is roadmap and not blank

geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/mymapsservice.js
=> Bad old bgLayer name

geoportailv3/static/js/print/printdirective.js
@rmichaelis can you please test in your working print environment
=> Piwik print tracking

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/imageupload/imguploaddirective.js, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/static/js/usermanagerservice.js
=> Mark string as translatable

geoportailv3/views/getfeatureinfo.py
=> Test if value exists

geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/querydirective.js
- Hide entry when no value
- Show a link with string starts with http or https
=> Improve automatic display

geoportailv3/static/js/query/attribute_values_for_translation.html, geoportailv3/static/js/query/parcels.html, geoportailv3/static/js/query/querydirective.js
To prefix or not to prefix, that is the question for @jaykayone
=> Translate values from PF

geoportailv3/static/js/query/querydirective.js
=> Display the layer label

geoportailv3.mk
@jaykayone is this what you are expecting ?
=> Add pull target

geoportailv3/static/js/query/querydirective.js, geoportailv3/views/getfeatureinfo.py
For direct link to the addresses
=> Layer is in the first occurence

geoportailv3/static/less/catalog.less
=> Remove bullet

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js
Fixes #1175 
Due to this : https://github.com/Geoportail-Luxembourg/geoportailv3/commit/6bba797c21a41df1ca5d5fdcd113767c56a08126
=> Create a map from anonymous

geoportailv3/static/js/locationinfo/locationinfodirective.js
=> X and Y are in LUREF in V2

geoportailv3/static/js/maincontroller.js
=> Use french instead of browser language

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/mymapsservice.js
=> Don't show an arrow on each vertex

geoportailv3/__init__.py, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/views/mymaps.py
=> Remove each element belonging to a mymaps

geoportailv3/views/wms.py
ip containing spaces are wrong
=> Remove trailing spaces

geoportailv3/static/js/search/searchdirective.js
=> Encode query before sending it

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/maincontroller.js
=> Deactivate the query tool as soon as a feature is selected

geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/draw/styleediting.html, geoportailv3/static/js/draw/styleediting.js
=> Add a reverse line button in the styling popup

geoportailv3/static/js/mymapsservice.js
=> Better error management

apache/wsgi.conf.mako, geoportailv3.mk, geoportailv3/__init__.py, geoportailv3/portail.py, geoportailv3/static/js/main.js, geoportailv3/static/js/query/pag.html, geoportailv3/static/js/query/pagreport.html, geoportailv3/static/js/query/reportdirective.js, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html, geoportailv3/views/pag.py, main.mk, vars_geoportailv3.yaml
=> PAG report generation

geoportailv3/static/js/themeswitcher/themes.html
After login the list of themes should be refreshed.
=> Themes list could be dynamically changed

geoportailv3/static/js/maincontroller.js
=> Avoid to reload themes at init time

geoportailv3/static/js/query/adresse.html, geoportailv3/static/js/query/aero.html, geoportailv3/static/js/query/affaires.html, geoportailv3/static/js/query/batiments.html, geoportailv3/static/js/query/bus.html, geoportailv3/static/js/query/cfl_hecto.html, geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/flik.html, geoportailv3/static/js/query/inst_pub.html, geoportailv3/static/js/query/meteo.html, geoportailv3/static/js/query/mo.html, geoportailv3/static/js/query/mymaps.html, geoportailv3/static/js/query/ng95.html, geoportailv3/static/js/query/ont_poi.html, geoportailv3/static/js/query/pagreport.html, geoportailv3/static/js/query/parcels.html, geoportailv3/static/js/query/parcels_go.html, geoportailv3/static/js/query/pcn_pag.html, geoportailv3/static/js/query/poi.html, geoportailv3/static/js/query/remembrements.html, geoportailv3/static/js/query/urplang.html, geoportailv3/static/js/query/viti_flik.html, geoportailv3/static/js/query/viti_kleinlage.html, geoportailv3/static/js/query/viti_name.html, geoportailv3/static/js/query/viti_parcels.html
@rmichaelis please review and merge :)
=> added link to map and target blanks

geoportailv3/static/js/query/querydirective.js
=> Clear the query result only when exclusion occures

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/views/mymaps.py
@jaykayone Could you please review and tell me if the admin concept works now as expected.
=> Check server side if the current user can modify the map

geoportailv3/views/getfeatureinfo.py
=> new function to add area information to a featureinfo popup

geoportailv3/static/less/geoportailv3.api.less, jsapi/config.json, jsapi/examples/marker.html, jsapi/examples/marker.js, jsapi/externs/luxx.js, jsapi/src/main.js
Adds a `showMarker`.
There may still need work on the `position` part about coordinate reference system.
@tonio Can you please review?
=> Show marker

geoportailv3.mk, jsapi/examples/marker.html, jsapi/examples/simple.html, jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/layers.json, jsapi/src/main.js, package.json
Adds:
- position
- positionSrs
- zoom
- bgLayer
- layers
- add `addLayerById` to `lux.Map` object.
=> Map configuration

geoportailv3/__init__.py, geoportailv3/templates/api/apiv3loader.js, geoportailv3/views/jsapi.py, jsapi/examples/marker.js, jsapi/examples/simple.js, jsapi/layers.json, jsapi/src/main.js
=> Jsapi layers

geoportailv3/templates/api/apiv3example.html, jsapi/config.json
=> Put ol and lux externs in the build

geoportailv3.mk, geoportailv3/static/less/geoportailv3.api.less, jsapi/config.json, jsapi/examples/marker.html, jsapi/examples/marker.js, jsapi/examples/simple.html, jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/main.js
- Add mouseposition control
- Make styles closer to main app
- Add logo
=> Add MousePosition control config

geoportailv3/templates/api/apiv3example.html, jsapi/examples/simple.js, jsapi/src/main.js
Fixes #1351.
@tonio please review.
=> Add support for names in layers config

jsapi/examples/simple.html, jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/main.js
=> Configure mouse position w/ an object w/ target mandatory

jsapi/externs/luxx.js
=> Simplify the externs, avoid duplication of information

geoportailv3/static/less/geoportailv3.api.less, jsapi/examples/simple.html, jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/main.js
=> Add Background selector

geoportailv3/static/less/geoportailv3.api.less, geoportailv3/templates/api/apiv3example.html, jsapi/examples/simple.html, jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/layermanager.js, jsapi/src/main.js
=> Add layer manager component

jsapi/externs/luxx.js, jsapi/src/main.js
=> Fix build errors

geoportailv3/static/js/mymaps/mymaps.html
=> Sort by category name

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/mymaps/mymaps.html
=> Scroll to the feature

geoportailv3/mymaps.py
=> Default value for linestyle is plain and not dotted

geoportailv3/static/js/mymaps/mymapsdirective.js
=> Center the view on the imported features

geoportailv3/static/js/statemanagerservice.js
=> Lang parameter should not override the localstorage

geoportailv3/static/js/activetoolservice.js, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/measure/measuredirective.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/templates/index.html
=> Improve activation of query tool startegy

geoportailv3/static/js/exportservice.js
=> Export some LineStrings instead of one multilinestring

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/exclusionmanagerservice.js, geoportailv3/static/js/imageupload/imguploaddirective.js, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/notifyservice.js, geoportailv3/static/js/query/reportdirective.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/static/less/notify.less
=> More flashy color proposal

development.ini.mako, production.ini.mako, setup.py
=> Add Sentry logging

jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/main.js
=> Add support for layer exclusions

jsapi/examples/feature.html, jsapi/examples/feature.js, jsapi/externs/luxx.js, jsapi/layers.json, jsapi/src/main.js
=> Add abililty to recenter on Feature

jsapi/src/main.js
=> Show marker options are optional

jsapi/src/main.js
Fixes search in built mode
Fixes #1431 
Please review.
=> Don't rename autocomplete config options

jsapi/examples/simple.js, jsapi/externs/luxx.js, jsapi/src/main.js
=> Add support for opacity for layers

geoportailv3/static/less/geoportailv3.api.less, jsapi/examples/mymaps.html, jsapi/src/mymap.js
Most of the code has been taken from featurepopup directive and export service.
Please review.
=> Add support for KML/GPX export in mymaps

geoportailv3/static/js/mymaps/mymaps.html
=> Default sort : by date

geoportailv3/static/js/query/bus.html
=> case sensitive

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/static/less/mymaps.less, geoportailv3/views/authentication.py, geoportailv3/views/mymaps.py
@jaykayone There is a new menu entry : "Edit object" 
Could you please check on dev/renaud and tell me if it works as you expect ?
=> Lock mymaps

geoportailv3/static/js/search/searchdirective.js
=> Parsefloat wants . instead of ,

geoportailv3/static/less/geoportailv3.api.less
=> Fix close button position in search input

jsapi/examples/simple.js, jsapi/src/main.js
=> Add support for external WMS layers

CONST_Makefile
Fixes #1471 
Here's a temporary fix for the error with pycparser.
@rmichaelis travis now turns green. Please review.
=> Don't fail when install pycparser

jsapi/examples/vector.js, jsapi/externs/luxx.js, jsapi/src/main.js
=> Add support for reloadInterval for GPX/KML layers

jsapi/externs/luxx.js, jsapi/src/main.js, jsapi/src/statemanager.js
=> Logo link becomes a permalink

jsapi/src/main.js
This pull request makes sure that the found address is highlighted on the map.
Also, we now make sure that only addresses are searched for.
Fixes #1452.
Please review.
=> Search highlight

geoportailv3/static/js/query/querydirective.js
=> Quit edit mode only by clicking on the dedicated button

geoportailv3.mk, geoportailv3/templates/api/apiv3loader.js, geoportailv3/templates/tooltip/batiments.html, geoportailv3/templates/tooltip/default.html, geoportailv3/views/getfeatureinfo.py, jsapi/examples/feature.js, jsapi/src/main.js
=> Allow server side generation of tooltip content

jsapi/src/statemanager.js
- Reverse order of layers,
- Use target _blank.
Fixes #1429 
Please review.
=> Jsapi permalink

jsapi/src/main.js
=> Allow blank layer to be set as bg layer

geoportailv3/templates/api/apiv3example.html, jsapi/examples/geocode.html, jsapi/examples/geocode.js, jsapi/externs/luxx.js, jsapi/src/main.js
Fixes #1442 
@tonio Please review.
=> JSAPI geocode / reverse geocode

jsapi/examples/common.js, jsapi/examples/feature.js, jsapi/examples/marker.js, jsapi/examples/mymaps.js, jsapi/examples/search.js, jsapi/examples/simple.js, jsapi/examples/vector.js, jsapi/src/main.js
Fixes #1496.
@tonio please review.
=> Set the base url only once

jsapi/examples/feature.js, jsapi/src/main.js
=> Highlight the shown features if corresponding layer is visible

geoportailv3/static/js/exportservice.js
=> Since this is corrected in OL3, it duplicates the schema definition

geoportailv3/models.py
=> Manage all tables with admin interface

jsapi/src/main.js, jsapi/src/statemanager.js
=> Permalink to take map_id into account

jsapi/src/main.js
=> Set default bg to 'basemap_2015_global'

jsapi/src/main.js
Due to wrong rebase
Fixes #1517.
=> Fix duplicated layermanager issue

jsapi/src/main.js
Fixes #1504.
I can't really test this on my side. @jaykayone Can you please give this branch a try?
=> Don't fail if geometry is used instead of bbox

geoportailv3/__init__.py, geoportailv3/static/js/layerlegends/layerlegends.html, geoportailv3/static/js/layerlegends/layerlegendsdirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/icons.less, geoportailv3/static/less/sidebar.less, geoportailv3/templates/index.html, geoportailv3/views/legends.py, setup.py
Fixes #903 
@jaykayone Could you please check on dev/renaud ?
What should I do with legends coming from geology ? 
Parse the html and remove the width from tables ?  
ex : 
http://devv3.geoportail.lu/renaud/theme/main?version=3&zoom=16&X=692753&Y=6381890&lang=fr&layers=314-272-702-199-359&opacities=0.9-1-1-1-1&bgLayer=blank&crosshair=false
=> Legend button

geoportailv3/static/less/geoportailv3.api.less, jsapi/examples/simple.js, jsapi/layers.json, jsapi/src/main.js
Fixes #1338.
This will need to be tested in real cases.
=> Add support for query on map

geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/themesservice.js, geoportailv3/static/less/geoportailv3.less
=> add attribution for new basemap_2016 with carto tiles and osm data

jsapi/examples/feature.js, jsapi/src/main.js
=> Add ability to set toolip popup size

jsapi/src/mymap.js
=> Fix select interaction in mymaps

geoportailv3/static/js/maincontroller.js
=> Deactivate map rotation

geoportailv3/static/js/draw/drawdirective.js
=> Stay in edit mode after drawing an object

geoportailv3/views/mymaps.py
=> Keep the feature id

jsapi/externs/luxx.js, jsapi/src/main.js
Fixes #1556, with a `popupTarget` config option for the map.
=> Allow to render popup in custom div

geoportailv3/static/less/geoportailv3.api.less, jsapi/src/main.js
=> Change cursor to pointer on every feature’s hovering

geoportailv3/static/js/search/searchdirective.js
=> Use same zoom level as in V2

geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/print/printdirective.js, geoportailv3/static/js/themesservice.js
_hd tiles are loaded if metadata property hasRetina is true AND device has retina screen
fix #1124
=> Retina tiles support for background layers

jsapi/src/main.js
=> Change cursor when hovering image (WMS/WMTS) features

development.ini.mako, geoportailv3/__init__.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/feedback/feedback.html, geoportailv3/static/js/feedback/feedbackdirective.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/sidebar.less, geoportailv3/templates/index.html, geoportailv3/views/feedback.py, setup.py, vars_geoportailv3.yaml
fix #1106
@rmichaelis 
Can you help me? I dont understand how to change the template for the popup from the one set for the [layerinfo template url](https://github.com/Geoportail-Luxembourg/geoportailv3/blob/3fd6f5c300914889cfb0210bc8388ab132c2b11e/geoportailv3/templates/index.html#L287)
According to [ngeo source code](https://github.com/camptocamp/ngeo/blob/87cdea826e091a7447e41f36fd2ce3fe0e54701f/src/directives/popup.js#L28) need to override the `ngeoPopupTemplateUrl` but didnt manage to do this successfully.
=> Feedback tool

geoportailv3.mk, geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/layout.less, geoportailv3/templates/index.html, vars_geoportailv3.yaml
Fixes #901 
Preview here : http://devv3.geoportail.lu/renaud
=> Basic overview map

geoportailv3/views/mymaps.py
=> Check that the feature exists

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/search/searchdirective.js, geoportailv3/static/js/themeservice.js, geoportailv3/static/js/themeswitcher/themeswitcherdirective.js
=> Scale is theme dependent

geoportailv3/static/js/askredirect/askredirect.html, geoportailv3/static/js/askredirect/askredirect.js, geoportailv3/static/js/locationcontrol.js, geoportailv3/static/js/main.js, geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html
Fixes #1535 
@jaykayone Could you please test redirect if not https ?
http://devv3.geoportail.lu/renaud
=> Fix geolocation

geoportailv3/static/js/usermanagerservice.js
=> If cookie has expired then reset user information

geoportailv3/static/js/statemanagerservice.js
Fixes #1266 
@jaykayone Could you please check on dev/renaud if it works as expected ?
=> Do not allow to start with a blank map

geoportailv3/static/js/draw/draw.html, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/navbars.less, geoportailv3/templates/index.html
Fixes #709 
@jaykayone Could you please check on dev/renaud
Could you please check the user experience with mobile as well as the desktop view.
=> Allow to draw and share with the mobile view

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/profile/profile.html, geoportailv3/static/js/profile/profiledirective.js
=> Use a different message.

geoportailv3/static/js/layerlegends/layerlegends.html, geoportailv3/static/js/layerlegends/layerlegendsdirective.js
=> Display a message when no legend is available.

geoportailv3/static/less/theme.less
=> Gray color sounds like button is deactivated

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/views/mymaps.py
=> Display the categories associated with the maps of current user

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/less/theme.less
=> Different color for the menu item

geoportailv3/static/js/geocodingservice.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/statemanagerservice.js, geoportailv3/templates/index.html
=> Recenter and provide information on a given address

geoportailv3/static/js/search/searchdirective.js
=> Mark the string available for translation

geoportailv3/static/js/print/printdirective.js, print/print-apps/geoportailv3/a0_landscape.jrxml, print/print-apps/geoportailv3/a0_portrait.jrxml, print/print-apps/geoportailv3/a1_landscape.jrxml, print/print-apps/geoportailv3/a1_portrait.jrxml, print/print-apps/geoportailv3/a2_landscape.jrxml, print/print-apps/geoportailv3/a2_portrait.jrxml, print/print-apps/geoportailv3/a3_landscape.jrxml, print/print-apps/geoportailv3/a3_portrait.jrxml, print/print-apps/geoportailv3/a4_landscape.jrxml, print/print-apps/geoportailv3/a4_portrait.jrxml, print/print-apps/geoportailv3/config.yaml
=> Translate print

geoportailv3/views/luxprintproxy.py
=> Use the title as file name.

geoportailv3/static/js/print/printdirective.js, print/print-apps/geoportailv3/a0_landscape.jrxml, print/print-apps/geoportailv3/a0_portrait.jrxml, print/print-apps/geoportailv3/a1_landscape.jrxml, print/print-apps/geoportailv3/a1_portrait.jrxml, print/print-apps/geoportailv3/a2_landscape.jrxml, print/print-apps/geoportailv3/a2_portrait.jrxml, print/print-apps/geoportailv3/a3_landscape.jrxml, print/print-apps/geoportailv3/a3_portrait.jrxml, print/print-apps/geoportailv3/a4_landscape.jrxml, print/print-apps/geoportailv3/a4_portrait.jrxml, print/print-apps/geoportailv3/config.yaml
=> Add current print date

jsapi/examples/ol3_api.html, jsapi/examples/ol3_api.js, jsapi/src/main.js
=> Don't add layer before layersPromise is resolved

jsapi/src/main.js
=> Export addLayerById

geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/statemanagerservice.js
If bgLayer and map_id parameter exists together then uses value from bgLayer.
=> Display bg layer from mymaps

geoportailv3/static/js/notifyservice.js, geoportailv3/static/less/notify.less
=> Better message notification on mobile

jsapi/src/main.js, jsapi/src/mymap.js
=> Wrong profile url

geoportailv3/static/js/coordinatestringservice.js, geoportailv3/static/js/infobar/projectionselectordirective.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/search/searchdirective.js
=> Add coordinate in decimal minutes representation

geoportailv3/static/js/search/searchdirective.js
=> Search DMS

geoportailv3/PF.py, geoportailv3/mymaps.py, geoportailv3/views/mymaps.py
Fixes #1566 
- download mesurage is ok
- Mymaps is ok
=> lowercase login comparison

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/maincontroller.js
=> Manage permalink with zoom higher than 19

geoportailv3/static/js/feedback/feedbackdirective.js
=> close and empty feedback form on successful send

geoportailv3.mk, geoportailv3/views/mymaps.py, vars_geoportailv3.yaml
Fixes #1662 
url and emails have to be configured in vars_*.yaml
cc is not mandatory
=> Send a notification when a map becomes public

geoportailv3/static/js/query/querydirective.js
=> Keep the same order for the query result as for the layer displayed

geoportailv3.mk, geoportailv3/__init__.py, geoportailv3/static/js/externaldata/externaldatadirective.js, geoportailv3/static/js/wmsservice.js, geoportailv3/templates/index.html, geoportailv3/views/wms.py, vars_geoportailv3.yaml
=> Proxy when map uses https and wms url uses http

geoportailv3/static/js/search/searchdirective.js, geoportailv3/views/fulltextsearch.py
fixes #1644
starting to fix #1388
=> Fix issues without ES backend upgrade

geoportailv3/__init__.py, jsapi/src/layermanager.js
=> Allow to set a layer title

jsapi/externs/luxx.js, jsapi/src/main.js
=> Layer name parameter

jsapi/examples/index.html, jsapi/externs/luxx.js, jsapi/src/main.js
=> Query or not the layers

jsapi/examples/index.html, jsapi/externs/luxx.js, jsapi/src/main.js
=> Add interaction only on the newly created layer

jsapi/examples/index.html, jsapi/externs/luxx.js, jsapi/src/main.js
=> Select the queryable layers

build.json, geoportailv3/externs/piwik.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/themeservice.js
=> Piwik tracking improvements

geoportailv3/static/js/query/default.html, geoportailv3/static/js/query/querydirective.js
=> Choose a new language should also change the feature language

geoportailv3/static/js/search/searchdirective.js
fix #1742 enter autocompletes first result
another press on enter then selects the result
=> Search Enter key autocompletes first result

geoportailv3/mymaps.py, geoportailv3/views/mymaps.py
=> Update feature with the login

geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/maincontroller.js
=> Keyboard interaction

geoportailv3/static/js/draw/drawdirective.js
Fixes #1774 
workaround for https://github.com/openlayers/openlayers/issues/6714
=> Does not allow to draw invalid geometry

geoportailv3/static/js/print/printdirective.js
=> Print bg legend

jsapi/examples/index.html, jsapi/externs/luxx.js
=> New examples displaying markers with different SRS

geoportailv3/__init__.py, geoportailv3/mymaps.py, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/less/layermanager.less, geoportailv3/views/mymaps.py
=> Feature ordering

geoportailv3/static/js/print/printdirective.js
=> Don't set 'open' and 'infoOpen' binded values to 'undefined'

geoportailv3/static/js/query/mymaps.html, geoportailv3/static/js/query/querydirective.js, geoportailv3/templates/index.html
=> Add a qr code for mymaps link

geoportailv3/static/less/featurepopup.less
=> Minimum height to be able to show the menu

geoportailv3/static/js/print/printdirective.js
=> Allow labels to overlap

geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/query/querydirective.js
Fixes #1779 
@petzlux @jaykayone @adonno Could you please test longpress as well as layer querry on different devices and browsers?
http://devv3.geoportail.lu/renaud
Thanks
=> Fix longpress

jsapi/examples/index.html, jsapi/externs/luxx.js, jsapi/src/main.js
=> Allow to search by coordinates

jsapi/src/main.js
Due to this : https://github.com/Pixabay/JavaScript-autoComplete/issues/35
=> Do not cache results

.travis.yml, LUX_alembic/versions/3e50ad660e39_missing_table_definition.py
=> Add the missing table definitions

geoportailv3/static/js/query/querydirective.js
=> Use french as fallback language

.eslintrc, build.json, geoportailv3.mk, geoportailv3/externs/jszip.js, geoportailv3/static/js/main.js, geoportailv3/static/js/mymaps/filereader.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/templates/index.html, package.json
=> Import KMZ

geoportailv3/templates/api/apiv3loader.js, jsapi/config.json, jsapi/src/main.js, jsapi/src/print.js, jsapi/src/statemanager.js
=> Api print v2

jsapi/src/main.js
=> Get piwik object from window object

geoportailv3/static/js/draw/drawdirective.js
=> Prevent only when Backspace or Escape was previously used

geoportailv3/static/js/query/querydirective.js, geoportailv3/views/getfeatureinfo.py
- Request a token to get external data from secured arcgis.
- Request OGC GetFeature Info when nothing else is configured.
=> Get feature info

geoportailv3/static/js/query/default_table.html
=> new layout

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/less/mymaps.less
=> Confirmation dialog box when deleting

geoportailv3/views/mymaps.py
=> Unicode error

geoportailv3/static/js/catalog/catalogdirective.js, geoportailv3/static/js/layerpermalinkservice.js
=> Reset to the original value when toggling

geoportailv3/static/js/externaldata/externaldata.html, geoportailv3/static/js/externaldata/externaldatadirective.js, geoportailv3/static/js/externaldata/wmstree.html, geoportailv3/static/js/externaldata/wmtstree.html, geoportailv3/static/js/layerinfo/layerinfoservice.js, geoportailv3/static/js/layerpermalinkservice.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/wmsservice.js, geoportailv3/static/js/wmtsservice.js, geoportailv3/static/less/mymaps.less, geoportailv3/templates/index.html
=> Accept wmts services

geoportailv3/static/js/catalog/layertree.html, geoportailv3/static/less/theme.less
=> Add an expand button up to 10 sublevels

geoportailv3/static/js/draw/clipinteraction.js, geoportailv3/static/js/draw/drawdirective.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/query/querydirective.js
=> Merge lines

geoportailv3/models.py, geoportailv3/views/luxprintproxy.py
=> get print servers info from db

geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/static/less/navbars.less, geoportailv3/templates/index.html
See https://jira.camptocamp.com/browse/GSLUX-6.
Based on https://github.com/camptocamp/luxembourg_geoportailv3/pull/2 , fix:
- toggling when a incompatible tool is already open
- toolbar appearance.
=> [3d] Hide and disable tools when 3d is active

jsapi/src/main.js
Some clients use html as value.
=> Remove title on td.

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/map/map.html, geoportailv3/static/js/map/mapdirective.js, geoportailv3/static/js/map/toogle3dcomponent.js, geoportailv3/static/less/layout.less, geoportailv3/static/less/navbars.less, geoportailv3/static/less/theme.less, geoportailv3/templates/index.html
=> Move 3d toggle button in the map.

CONST_Makefile, geoportailv3/static/js/infobar/elevationdirective.js, geoportailv3/static/js/infobar/projectionselector.html, geoportailv3/static/js/infobar/projectionselectordirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/map/map.js, geoportailv3/static/less/geoportailv3.less
For mouse coordinate & elevation.
=> [3d] Enable infobar in 3D

geoportailv3/static/js/appmodule.js, geoportailv3/static/js/layerfactoryservice.js, geoportailv3/static/js/map/map.js, geoportailv3/static/js/wmsservice.js, geoportailv3/static/js/wmtsservice.js, package.json
Depends on https://github.com/openlayers/ol-cesium/pull/542.
=> Limit raster extent

jsapi/src/main.js
Provide a way to access the clear button.
=> new parameter

geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/query/querydirective.js
This causes issue with the permalink, as all layers in layer manager are added to the permalink.
=> Remove vector layers (info & query) from layer manager

geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/query/querydirective.js
=> Make mymaps visible in 3D.

geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/locationinfo/locationinfodirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/less/geoportailv3.less, geoportailv3/templates/index.html
=> 3d mymaps: readonly mode

geoportailv3/static/less/geoportailv3.less
By adding missing css rule from ol-cesium.
=> [3d] Avoid duplicate overlays

geoportailv3/static/js/locationinfo/locationinfo.html, geoportailv3/static/js/locationinfo/locationinfodirective.js
=> Add link to travel planer on mobiliteit

geoportailv3/static/js/mymaps/mymapsdirective.js
Needs to be merged to check on dev instance.
=> [3d] Fix vector layer being detached

geoportailv3/templates/index.html, package.json
See https://jira.camptocamp.com/browse/GSLUX-40.
=> Use stacked ground corridors

geoportailv3/__init__.py, geoportailv3/static/js/search/searchdirective.js, geoportailv3/templates/index.html, geoportailv3/views/fulltextsearch.py
Now the search bar integrates as well the CMS page results
=> Petzlux cms search

geoportailv3/mymaps.py, geoportailv3/views/authentication.py, geoportailv3/views/mymaps.py
@jaykayone Are you able to check this branch in your docker environment  ?
=> Fallback mymaps role when ldap is not configured

geoportailv3/static/js/draw/featurepopup.html
=> [3d] Avoid edition of feature in 3D

geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/less/featurepopup.less
=> [3d] Avoid page reload on popup close

geoportailv3/static/js/mymapsservice.js, package.json
Fixes: https://jira.camptocamp.com/browse/GSLUX-40.
Related to: https://jira.camptocamp.com/browse/GSLUX-54.
=> Fix some my maps issues

geoportailv3/static/js/layerpermalinkservice.js
=> Fix layer order

geoportailv3/views/routing.py
=> Add missing parameter

geoportailv3/static/js/olcs/lux3dmanager.js
See https://jira.camptocamp.com/browse/GSLUX-62.
=> Fix the sun position so that illumination is always nice

geoportailv3/templates/index.html
See https://jira.camptocamp.com/browse/GSLUX-61.
=> Use https for 3d tilesets

vars_c2cdev.yaml
I've also created a "offline" branche in the lux_db project
So I can use the mymaps system.
=> Use 'lux' as mymaps db for c2c dev

geoportailv3/static/js/maincontroller.js, geoportailv3/static/less/offline.less, geoportailv3/templates/index.html, package.json
Integrate ngeo NetworkStatus service to detect when offline.
Must wait the ngeo PR is merged.
https://github.com/camptocamp/ngeo/pull/3909
=> Add Network Status for offline mode

geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymapsserviceoffline.js, geoportailv3/static/js/offlineRestorer.js
GSLUX-82
Tested via the code in the temporarily PR: https://github.com/camptocamp/ngeo/pull/3968 And Now I can restore the mymaps as expected :-)
=> Restore mymaps

geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/infobar/infobar.html, geoportailv3/static/js/infobar/infobardirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/less/offline.less, geoportailv3/templates/index.html
=> Disable some functionalities when offline

geoportailv3/static/js/mymapsserviceoffline.js
=> Mymaps use storage

geoportailv3/static/js/maincontroller.js, package.json
=> Offline fix offline panel swicth and update ngeo

geoportailv3/static/js/offlineNgeoComponent.html, geoportailv3/templates/index.html
GSLUX-88
I've copied the file, that's the only template in this case. This solution should be enough, the template is now in `.build/build.js`
=> Copy ngeo offline component html here - caching purpose

geoportailv3/static/js/maincontroller.js, geoportailv3/templates/index.html, package.json
See details in https://github.com/camptocamp/ngeo/pull/3965
=> Offline: Fixed mask (as gmap) and zoom constraints for offline mode

geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/mymapsserviceoffline.js
GSLUX-72
Don't add feature if there is already feature on the map
=> Clear mymaps before to add offline features

geoportailv3/static/js/print/printdirective.js, geoportailv3/static/js/print/printservice.js
Sort by z-index is not reported in the ngeo version we use.
=> Use z-index in print

geoportailv3/static/js/appmodule.js, geoportailv3/templates/geoportailv3.appcache
See https://jira.camptocamp.com/browse/GSLUX-114.
=> Fix appcache

geoportailv3/static/less/offline.less
See https://jira.camptocamp.com/browse/GSLUX-109.
=> Hide the KML/GPX download feature when offline

package.json
See https://jira.camptocamp.com/browse/GSLUX-111 and  https://jira.camptocamp.com/browse/GSLUX-112.
=> Fix activation right after download

package.json
Get the fixes for the issues not catched by Travis.
=> Offline fixes

geoportailv3/static/js/offline/Configuration.js, geoportailv3/static/js/offlineNgeoComponent.html, package.json
GSLUX-116
Need and wait on: https://github.com/camptocamp/ngeo/pull/4040
Now if you have a mymaps 5MB is added to the size to download.
And the "blank" bg layer count as 0MB.
So if you have the "blank" bg layer, no layer and no mymap, the size is 0MB and ngeo display a popup that prevent you to download anything.
=> Better calculation of size to download

package.json
See https://jira.camptocamp.com/browse/GSLUX-110.
=> Update ngeo to fix retina extent issue

geoportailv3/templates/geoportailv3.appcache
See  https://jira.camptocamp.com/browse/GSLUX-118.
=> Fix themes caching

geoportailv3/static/js/offlineRestorer.js, geoportailv3/static/less/offline.less, package.json
Adress:
https://jira.camptocamp.com/browse/GSLUX-123
https://jira.camptocamp.com/browse/GSLUX-126
https://jira.camptocamp.com/browse/GSLUX-127
https://jira.camptocamp.com/browse/GSLUX-128
Need to be based on ngeo https://github.com/camptocamp/ngeo/pull/4060
=> Offline fix

geoportailv3/static/js/mymaps/mymapsdirective.js
If not done, on touch screen, we cannot interact with the elements such as text or textarea inside the modal.
=> For the mymaps modal, activate the drag handler only on the H4 element

CONST_Makefile, geoportailv3/static/less/sidebar.less
=> No background

.jshintrc, geoportailv3/__init__.py, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/mymapsserviceoffline.js, geoportailv3/static/less/offline.less, geoportailv3/templates/index.html, geoportailv3/views/mymaps.py
For GSLUX-175
Ongoing. Todo list in the jira ticket.
=> Multi mymaps offline

.env-default, .gitignore, README.md, docker-compose.yaml, geoportal/Dockerfile, geoportal/config.yaml, geoportal/geoportailv3_geoportal/__init__.py, geoportal/geoportailv3_geoportal/mymaps.py, geoportal/geoportailv3_geoportal/views/authentication.py, geoportal/geoportailv3_geoportal/views/mymaps.py, geoportal/geoportailv3_geoportal/views/routing.py
See https://jira.camptocamp.com/browse/GSLUX-190.
=> Restore LDAP functionnality

geoportailv3/__init__.py, geoportailv3/static/js/appmodule.js, geoportailv3/static/js/draw/drawnfeaturesservice.js, geoportailv3/static/js/draw/featurepopup.html, geoportailv3/static/js/draw/featurepopupdirective.js, geoportailv3/static/js/imageupload/imguploaddirective.js, geoportailv3/static/js/maincontroller.js, geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/mymapsserviceoffline.js, geoportailv3/static/js/query/querydirective.js, geoportailv3/static/js/usermanagerservice.js, geoportailv3/static/less/mymaps.less, geoportailv3/static/less/offline.less, geoportailv3/views/mymaps.py, package-lock.json, package.json
While offline, allow to:
When back online:
=> [partial] Allow editing maps while offline

geoportailv3/static/js/mymaps/mymaps.html, geoportailv3/static/js/mymaps/mymapsdirective.js, geoportailv3/static/js/mymapsservice.js, geoportailv3/static/js/mymapsserviceoffline.js, geoportailv3/views/mymaps.py
https://jira.camptocamp.com/browse/GSLUX-193
https://jira.camptocamp.com/browse/GSLUX-215
Not including the update handling.
=> Sync backend offline (Add and delete)

geoportailv3/static/js/mymaps/mymapscontroller.js
Properly import kml by removing old workaround.
fixed by https://github.com/openlayers/openlayers/issues/6959
=> Properly import KMl

geoportal/geoportailv3_geoportal/static-ngeo/js/Mymaps.js, geoportal/geoportailv3_geoportal/static-ngeo/js/MymapsOffline.js, geoportal/geoportailv3_geoportal/views/mymaps.py
https://jira.camptocamp.com/browse/GSLUX-230
=> GSLUX-230: Delete all features offline

geoportal/geoportailv3_geoportal/static-ngeo/js/infobar/ElevationController.js
https://jira.camptocamp.com/browse/GSLUX-228
=> Fix elevation

Makefile, geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/LuxRasterSynchronizer.js, geoportal/package.json
See https://jira.camptocamp.com/browse/GSLUX-260.
=> Basic 3d mvt

geoportal/geoportailv3_geoportal/static-ngeo/js/print/Printservice.js
See https://jira.camptocamp.com/browse/GSLUX-259.
=> Basic 3d mvt print

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js
See https://jira.camptocamp.com/browse/GSLUX-262.
=> Replace raster layer by vector one

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/backgroundlayer/BackgroundlayerController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/backgroundlayer/backgroundlayer.html, geoportal/geoportailv3_geoportal/static-ngeo/js/backgroundlayer/backgroundlayerDirective.js, geoportal/geoportailv3_geoportal/static-ngeo/js/print/Printservice.js, geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less
https://jira.camptocamp.com/browse/GSLUX-265
=> GSLUX-265: import style

geoportal/geoportailv3_geoportal/static-ngeo/intermediate_editor_spec.md, geoportal/geoportailv3_geoportal/static-ngeo/js/StateManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/mvtstyling/MediumStyleController.js, geoportal/geoportailv3_geoportal/static-ngeo/jsconfig.json, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
See https://jira.camptocamp.com/browse/GSLUX-272.
=> Intermediate style editor

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/mvtstyling/SimpleStyleController.js, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less, geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less
See https://jira.camptocamp.com/browse/GSLUX-273.
=> Add simple style selector

geoportal/geoportailv3_geoportal/static-ngeo/js/UserManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/authentication/AuthenticationController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less
This PR add the following improvements:
- Fix an issue on mobile interface
- Log in now load the mvt style from database
- Fix some syntax and remove some bind()
- Better clear mvt style now don't call the database endpoint when not logged
=> GSLUX-277: layout problem and various fixes

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
See https://jira.camptocamp.com/browse/GSLUX-279.
=> Fix surface style

geoportal/config.yaml, geoportal/geoportailv3_geoportal/static-ngeo/js/resizemapDirective.js, geoportal/package.json
See https://jira.camptocamp.com/browse/GSLUX-278.
=> Fix mapbox resize

Makefile, README.md, docker-compose.yaml, geoportal/Dockerfile, geoportal/bin/eval-templates, geoportal/geoportailv3_geoportal/templates/api/apiv3loader.js, geoportal/jsapi/closure/README.md, geoportal/jsapi/closure/asserts.js, geoportal/jsapi/closure/base.js, geoportal/jsapi/closure/deps.js, geoportal/jsapi/closure/depswriter.py, geoportal/jsapi/closure/error.js, geoportal/jsapi/closure/nodetype.js, geoportal/jsapi/closure/source.py, geoportal/jsapi/closure/string.js, geoportal/jsapi/closure/treescan.py, geoportal/jsapi/rebuild_api.sh, geoportal/jsapi/src/printmanager.js
We still can have a real debug mode but at least it is possible to "quickly" rebuild the API without restarting the composition.
Updating the example is even quicker; simply do this in the container:
cp -R /app/apiv3/jsapi/examples /app/geoportailv3_geoportal/jsapi/build/apidoc/
=> Jsapi cleanup

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
See https://jira.camptocamp.com/browse/GSLUX-280.
=> Array of paths

geoportal/config.yaml, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/js/print/Printservice.js
See https://jira.camptocamp.com/browse/GSLUX-252.
=> Print custom style

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/LuxRasterSynchronizer.js
See https://github.com/Geoportail-Luxembourg/geoportailv3/pull/2416.
=> Use custom XYZ in 3D

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
See https://jira.camptocamp.com/browse/GSLUX-283.
=> Restore appcache for ios and disable mvt

Makefile, README.md, geoportal/jsapi/examples/index.html, geoportal/jsapi/externs/luxx.js, geoportal/jsapi/layers.json, geoportal/jsapi/rebuild_api.sh, geoportal/jsapi/src/map.js, geoportal/jsapi/src/printmanager.js
See https://jira.camptocamp.com/browse/GSLUX-255 and https://jira.camptocamp.com/browse/GSLUX-264.
=> Jsapi impression

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
See https://jira.camptocamp.com/browse/GSLUX-286.
=> Some styling fixes

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
See https://jira.camptocamp.com/browse/GSLUX-286.
=> Allow coloring background

geoportal/jsapi/src/map.js
- Remove Highlight when no result is returned
- console.assert error
- Do not query when layer opacity is set to 0
=> Some fixes for api query

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less, geoportal/geoportailv3_geoportal/static-ngeo/less/theme.less
=> The font style depends of the themes

geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
See https://jira.camptocamp.com/browse/GSLUX-290.
=> Fix print not working

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/offlineNgeoComponent.html
See https://jira.camptocamp.com/browse/GSLUX-287.
=> Enable mvt for ios and warn

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/LayermanagerController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/layermanager.html, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/layermanagerDirective.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/less/layermanager.less, geoportal/geoportailv3_geoportal/static-ngeo/less/sidebar.less
https://jira.camptocamp.com/browse/GSLUX-304
=> GSLUX-304: background in my layers

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/share/ShareController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/share/share.html, geoportal/geoportailv3_geoportal/static-ngeo/js/share/shorturl.html, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less, geoportal/geoportailv3_geoportal/static-ngeo/less/layout.less
& add widget to get iframe HTML code for current application state.
GSLUX-327, GSLUX-328
=> Allow app to be simplified to be embedded in Iframe

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less, geoportal/geoportailv3_geoportal/static-ngeo/less/layout.less
- Avoid flickering header/footer on load
- Disable right click
- Neutral embedded popup theme
=> [c2cnextprod] Embedded mode improvements

geoportal/jsapi/externs/luxx.js, geoportal/jsapi/src/map.js
=> [c2cnextprod] add view rotation support in API

geoportal/jsapi/src/mymap.js
bypass this https://github.com/openlayers/openlayers/issues/1988
=> Cannot use two select interactions at the same time

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
https://jira.camptocamp.com/browse/GSLUX-353
=> Changement style 3d

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
https://jira.camptocamp.com/browse/GSLUX-366
=> Fix selected simple styles

geoportal/geoportailv3_geoportal/static-ngeo/less/layout.scss, geoportal/geoportailv3_geoportal/static-ngeo/less/navbars.scss
=> Tweak CSS to remove the scroll due to footer override

config/print/print-apps/geoportailv3/config.yaml.tmpl
=> Avoid extra blank page in landscape layout

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/print/PrintController.js
https://jira.camptocamp.com/browse/GSLUX-372
First commit is just a little cleanup, does not fix anything.
To test, just open the print panel with a serialized config in the permalink and a non-vector tile active background.
=> Error print in console

geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/catalog/CatalogController.js
Had to set it to all the instances of view created across the project, otherwise it would just not set the rotation and remove it to default value (0 but not the 0 provided from me at 'rotation' variable creation).
https://jira.camptocamp.com/browse/GSLUX-373
=> Rotation in permalink

geoportal/luxembourg_requirements.txt
@rmichaelis Cette branche devrait fixer le pb de comportement dans l'admin. Pourrais-tu essayer et me faire un retour? Merci.
=> Fix select behavior in GMF admin

docker-compose.yaml, geoportal/Dockerfile
Also remove PGOPTIONS env which breaks db connection.
=> reactivate the jsapi

geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less
=> fix: mobile buttons unexpectedly showing on desktop app

geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js
That breaks loading layers from permalink.
GSLUX-383
=> fix: avoid hidden layer to be wrongly added to permalink

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js
https://jira.camptocamp.com/browse/GSLUX-382
To tests, you will need to check these various use case:
- empty permalink + filled local storage -> load local storage style
- filled permalink + empty local storage -> load permalink style
- filled permalink + filled local storage -> load permalink style
- empty permalink + empty local storage -> load default style
=> Correctly load permalink-shared style  instead of the local storage style

geoportal/geoportailv3_geoportal/static-ngeo/js/Mymaps.js
see https://jira.camptocamp.com/browse/GSLUX-388
=> ugly but mandatory

docker-compose.yaml, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/search/search.html, geoportal/geoportailv3_geoportal/static-ngeo/js/search/searchDirective.js, geoportal/geoportailv3_geoportal/static-ngeo/less/geoportailv3.less, geoportal/geoportailv3_geoportal/static-ngeo/less/search.less, geoportal/geoportailv3_geoportal/static-ngeo/less/theme.less, geoportal/geoportailv3_geoportal/views/fulltextsearch.py
=> Faceted search.

geoportal/geoportailv3_geoportal/static-ngeo/js/MockProvider.js, geoportal/geoportailv3_geoportal/static-ngeo/js/module.js
GSLUX-361
Seems it was removed from ngeo 2.5 then from the project with migration by Guillaume. Just added it back to the project.
We need to check why we need anchorScroll in DrawController, as there is possibly  some issues with that as the comments in the file I copied mentionned.
=> Fix permalink parameters disappearing

geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/LuxRasterSynchronizer.js, geoportal/package.json
=> Make wintermesh 3D work as expected

geoportal/LUX_alembic/versions/4ae372fbc6fc_feature_search_attribute.py, geoportal/config.yaml, geoportal/geoportailv3_geoportal/__init__.py, geoportal/geoportailv3_geoportal/models.py, geoportal/geoportailv3_geoportal/static-ngeo/js/CoordinateMatch.js, geoportal/geoportailv3_geoportal/static-ngeo/js/routing/RoutingController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/geoportailv3_geoportal/views/fulltextsearch.py
search features in selected layers
operational for 
- ESRI rest layers
- postgis DB layers
pure WMS layer using the ogc proxy cannot be searched.
Configuration menu for search in POI, layers, features, CMS has to be harmonized with PR https://github.com/Geoportail-Luxembourg/geoportailv3/pull/2533
=> Features Search in selected Layers

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/search/search.html, geoportal/geoportailv3_geoportal/static-ngeo/js/search/searchDirective.js, geoportal/geoportailv3_geoportal/views/fulltextsearch.py
- allow query with spaces
- add more facets
- remove obsolete config
see GSLUX-391 & GSLUX-393
=> [Nextprod] fix elasticsearch config

geoportal/LUX_alembic/versions/4ae372fbc6fc_feature_search_attribute.py
downgrade table was incorrect in alembic script
=> Bugfix Alembic version

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
Change the default topomap styling config, added a new tag for symbols (text and icons) as inspired by fills and lines
=> Topomap default styling

geoportal/geoportailv3_geoportal/views/luxthemes.py
Fake capabilities for OGC server "Internal WMS" as capabilities is not available for this WMS proxy.
@tonio (for review)
=> Fix themes.json with internal WMS

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/geoportailv3_geoportal/views/fulltextsearch.py
Bugfixes according to comments in https://jira.camptocamp.com/browse/GSLUX-392
Corrections for the following problems:
- fix case insensitive search
- fix bbox for empty geometries
- fix id if missing
- enable extent filter for feature search
=> Fix featuresearch 2

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/geoportailv3_geoportal/views/fulltextsearch.py
fix projection and url encoding of feature search
=> Fix featuresearch 3

geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/js/utils.js
Tests I did and result:
URL only
- roadmap medium -> OK
- roadmap uuid -> OK
- topo medium -> NOK (URL browser limit > 4094 characters)
- topo uuid -> OK
LS only:
- roadmap medium -> OK
- roadmap uuid -> OK
- topo medium -> OK
- topo uuid -> OK
DB only:
- roadmap medium -> OK
- roadmap uuid -> OK
- topo medium -> OK
- topo uuid -> OK
Load URL, LS different
- roadmap -> OK
- topo -> OK
Load URL, DB different
- roadmap -> OK
- topo -> OK
Login with DB -> OK
Logout with DB -> OK
=> Other vector layers

geoportal/config.yaml, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/catalog/CatalogController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/catalog/layertree.html, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/LayermanagerController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/layermanager.html, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js
Please, @tonio @llienher @mki-c2c test the performance since it seems way better to me (but only tested on my laptop).
It lacks history though.
=> 3d in Catalog/layertree

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js
fix translation
try & error fixes to review:
https://github.com/Geoportail-Luxembourg/geoportailv3/compare/af7b3f6...fix_featuresearch_4
=> add translation

geoportal/luxembourg_requirements.txt
Avoid errors by fixing the pykwalify version
=> Fix the pykwalify version

geoportal/geoportailv3_geoportal/static-ngeo/js/catalog/CatalogController.js
=> Remove The right layer

geoportal/geoportailv3_geoportal/views/upload.py
let the style point to the local disk instead of the vectortiles url
=> Fix upload vt style

geoportal/geoportailv3_geoportal/views/getfeatureinfo.py
Fix performance issue when converting some complex esri geometries to geojson.
Instead of using the python function 'arcgis2geojson',  use the geojson generated by the esri remote service. 
This cannot be used with each service, because some remote servers don't manage geojson output (ANF)
geojson output  is used when url contains f=geojson
=> Performance issue

doc/conf_db.md, geoportal/geoportailv3_geoportal/static-ngeo/js/Themes.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js, geoportal/geoportailv3_geoportal/views/luxthemes.py, geoportal/vars.yaml
setup configuration of terrain tiles URL in admin interface.
=> Gslux 485 configure terrain

geoportal/geoportailv3_geoportal/static-ngeo/js/Mymaps.js, geoportal/geoportailv3_geoportal/static-ngeo/js/draw/StyleEditingController.js
PR fixes the following bugs:
- mymaps: checkbox "Afficher orientation" for line styles
=> Bug fixes related to Angularjs 1.8 migration

doc/conf_db.md, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/misc/WMSTime.js, geoportal/geoportailv3_geoportal/views/luxthemes.py
=> Fix time layers

geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/LayermanagerController.js, geoportal/geoportailv3_geoportal/views/wms.py
parse time range for internal WMS layers.
Works for both WMS and arcgis rest layers
=> Fix internal time range

doc/conf_db.md, geoportal/geoportailv3_geoportal/static-ngeo/less/layermanager.less, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/contribs/gmf/src/layertree/timeSliderComponent.js, geoportal/geoportailv3_geoportal/views/luxthemes.py
date set to now on specific metadata
=> Timeslider enable current date

geoportal/geoportailv3_geoportal/views/luxthemes.py
Reverts Geoportail-Luxembourg/geoportailv3#2931
=> Revert "Remove unused WMS getCapabilities"

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline-alert.component.ts, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline-error.component.ts, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline-reload.component.ts, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline.component.ts, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline.model.ts, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/lux-offline/lux-offline.service.ts, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.de.json, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.en.json, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.fr.json, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/locales/app.lb.json
PR displays a modal to the user if an error during the vector tile downloads occurred, that is, when the local backend answers with an inconsistent response.
=> [Offline mode] Inform the user if an error occured

geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/offline/SerializerDeserializer.js
Properly serialize Infinity values.  
examples : minZoom or maxZoom
=> Properly serialize Infinity values.

geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs
https://jira.camptocamp.com/browse/GSLUX-585
Merge this PR once https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/55 is merged into main only.
=> GSLUX-585: Layer comparator

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/geoportailv3_geoportal/static-ngeo/less/print.less, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/map/scaleselector.js
https://jira.camptocamp.com/browse/GSLUX-626
=> GSLUX-626: InfoBar (scale et elevation)

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/package.json
fix search service for background layers and other layers.
3d layers not working in search (but this is as in prod)
=> Gslux 651 search service

geoportal/geoportailv3_geoportal/static-ngeo/js/search/SearchController.js, geoportal/package.json
This PR is linked to https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/84
https://jira.camptocamp.com/browse/GSLUX-661
Selecting a Pois in the search suggestion should add the layer in the layer manager.
=> GSLUX-661: [Fix] Search on Pois should add the layer

geoportal/package.json
Linked to https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/86
https://jira.camptocamp.com/browse/GSLUX-650
=> GSLUX-650: Time layers on map

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/main.html.ejs, geoportal/package.json
Linked to https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/88
https://jira.camptocamp.com/browse/GSLUX-671
=> GSLUX-671: Fix modale display

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-664
This PR needs: https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/95
=> GSLUX-664: Proxyurl as a setting from v3

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
https://jira.camptocamp.com/browse/GSLUX-663
Force reload and refresh themes in themes selector each time the user logs in or logs out.
=> GSLUX-663: Reload themes on user login and logout

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
=> GSLUX-601: Fix rebase

geoportal/package.json
https://jira.camptocamp.com/browse/GSLUX-634
Update lux lib dep for https://github.com/Geoportail-Luxembourg/luxembourg-geoportail/pull/104
=> GSLUX-634: Update catalog on login logout

docker-compose.yaml, env.default, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/package.json, geoportal/vars.yaml
[GSLUX-698](https://jira.camptocamp.com/browse/GSLUX-698)
Avoid saving style on prod server.
=> GSLUX-698: update mvt urls to avoid saving on prod

docker-compose.yaml, env.default, geoportal/geoportailv3_geoportal/__init__.py, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/views/upload.py, geoportal/package.json, geoportal/vars.yaml
fix problem with style URL registration
=> Gslux 698 fix mvt urls

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
Erro introduced in rebase of https://github.com/Geoportail-Luxembourg/geoportailv3/pull/3151
=> Fix rebase error

geoportal/geoportailv3_geoportal/views/upload.py
fix incorrect url substitution due to hard-coded style server URL
=> GSLUX-698: fix url substitution in style file

geoportal/geoportailv3_geoportal/lib/sw_helper.py
=> GSLUX-713: put necessary offline files into cache also in prod

geoportal/geoportailv3_geoportal/static-ngeo/js/query/casiporeport.html, geoportal/geoportailv3_geoportal/static-ngeo/js/query/foragevirtuelreport.html, geoportal/geoportailv3_geoportal/static-ngeo/js/query/pagreport.html, geoportal/geoportailv3_geoportal/static-ngeo/js/query/pdsreport.html, geoportal/geoportailv3_geoportal/templates/tooltip/pag.html, geoportal/package.json
Override tailwind preflight css for v3:
- deactivate tailwind preflight css when build lib
- use custom preflight for lib
To test locally, use tweak chrome plugin :
=> GSLUX-725: Fix button and h1 styles

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
Force update angular scope in watcher for theme name.
=> GSLUX-724: Fix theme name

geoportal/package.json
use corresponding release in V4
=> fix raster style for non vector layers

geoportal/geoportailv3_geoportal/lib/sw_helper.py, geoportal/geoportailv3_geoportal/static-ngeo/js/OfflineRestorer.js, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/MapboxOffline.js, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/src/offline/component.js
corrections for offline BG layers
- style must be reloaded for vector layers
- localforage loader function shall be kept for tile layers
=> Gslux 716 fix offline bg

geoportal/package.json
https://camptocamp.atlassian.net/browse/GSLUX-759 plus https://camptocamp.atlassian.net/browse/GSLUX-760
=> GSLUX-759: Fix metadata

geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js
https://jira.camptocamp.com/browse/GSLUX-763
Trigger piwik addLayer in v4 watcher (otherwise layers definitions is not ready due to setThemes() done later).
=> GSLUX-763: Fix addlayer piwik

geoportal/geoportailv3_geoportal/views/geocode.py
Because the remote service may stay pending
=> reduce the timeout

geoportal/geoportailv3_geoportal/static-ngeo/js/GetShorturlService.js, geoportal/geoportailv3_geoportal/static-ngeo/js/LayerPermalinkManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/StateManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/apps/MainController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/askredirect/AskredirectController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/draw/DrawnFeatures.js, geoportal/geoportailv3_geoportal/static-ngeo/js/feedback/FeedbackController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/feedbackage/FeedbackageController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/feedbackanf/FeedbackanfController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/feedbackcrues/FeedbackcruesController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/layermanager/LayermanagerController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/locationinfo/LocationinfoController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/mvtstyling/MvtStylingService.js, geoportal/geoportailv3_geoportal/static-ngeo/js/offline/Configuration.js, geoportal/geoportailv3_geoportal/static-ngeo/js/olcs/Lux3DManager.js, geoportal/geoportailv3_geoportal/static-ngeo/js/query/QueryController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/share/ShareController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/share/ShorturlController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/slider/SliderController.js, geoportal/geoportailv3_geoportal/static-ngeo/js/themeswitcher/ThemeswitcherController.js, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/contribs/gmf/examples/layertree.js, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/contribs/gmf/examples/layertreeadd.js, geoportal/geoportailv3_geoportal/static-ngeo/ngeo/contribs/gmf/src/controllers/AbstractAppController.js
ngeolocation conflicts with urlstorage of v4 library. Then remove all occurrences of ngeolocation.
=> gets rid of ngeolocation
